apiVersion: projectcalico.org/v3
kind: BGPConfiguration
metadata:
  name: default
spec:
  logSeverityScreen: Info
  nodeToNodeMeshEnabled: false
  asNumber: 188
  serviceClusterIPs:
    - cidr: 10.18.0.0/16
  serviceExternalIPs:
    - cidr: 10.88.0.0/16
  listenPort: 178
  bindMode: NodeIP
