apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - image: 10.3.18.63/docker/nginx:v1.24
    name: test-container
    extraVolumeMounts:
    - mountPath: /etc/nginx/conf.d/defualt.conf
      name: conf   
    volumeMounts:

    - mountPath: /home 
      name: home
    - mountPath: /var/log/nginx
      name: log
    extraVolumes:
    - name: conf
      nfs:
        server: 10.145.254.55
        path: /home/nfsroot/nginx/conf/default.conf     



  volumes:

  - name: home
    nfs:
      server: 10.145.254.55
      path: /home/nfsroot/nginx/assets
      readOnly: false
  - name: log
    nfs:
      server: 10.145.254.55
      path: /home/nfsroot/nginx/log
      readOnly: false

