apiVersion: apps/v1
kind: Deployment
metadata:
  name: TDXuwsgi-deployment
spec:
  selector:
    matchLabels:
      app: TDXuwsgi
  replicas: 1 # 告知 Deployment 运行 2 个与该模板匹配的 Pod
  template:
    metadata:
      labels:
        app: TDXuwsgi
    spec:
      containers:
      - name: TDXuwsgi
        image: 10.3.18.63/docker/tdx-uwsgi:v1
        ports:
        - containerPort: 3031
        volumeMounts:
        - mountPath: /home 
          name: home
      volumes:
      - name: home
        nfs:
          server: 10.145.254.55
          path: /home/nfsroot/www
          readOnly: true
        
---
apiVersion: v1
kind: Service
metadata:
   name: TDXuwsgi-svc
   namespace: default
spec:
   type: ClusterIP
   clusterIP: 10.88.8.8
   selector:
      app: TDXuwsgi
   ports:
   - name: TDXuwsgi-server
     protocol: TCP
     port: 80
     targetPort: 3031