[uwsgi]
uid = ts
master = true

socket = 10.145.254.52:3031
chmod-socket = 755
socket-timeout = 3
processes = 2
cacuum = true
thunder-lock = true
enable-threads = true
pidfile = uwsgi.pid
daemonize = /tmp/uwsgi.log
#logto = /home/ts/app/www/uwsgi/uwsgi.log


chdir = /home/ts/app/test_app
wsgi-file = views.py
callable=app