upstream uwServers{    

   server 127.0.0.1:3031;
#    server 10.3.18.65:3031;

    }

server {
    listen 80;
    server_name k8s;
    charset utf-8;
    location ~.*\.(js)$ {
        root   /home;
        autoindex on;
       }


        location / {
                include uwsgi_params;
                uwsgi_pass uwServers;
         }
        location /status {
#           vhost_traffic_status_display;
#          vhost_traffic_status_display_format html;
           stub_status; 
} 

 }

