apiVersion: apps/v1
kind: Deployment
metadata:
  name: tdxscrape-deployment
spec:
  selector:
    matchLabels:
      app: tdxscrape
  replicas: 1 # 告知 Deployment 运行 2 个与该模板匹配的 Pod
  template:
    metadata:
      labels:
        app: tdxscrape
    spec:
      containers:
      - name: tdxscrape
        image: 10.3.18.60/docker/tdx-crawler:v3
        volumeMounts:
        - mountPath: /home 
          name: home
        - mountPath: /var/spool/cron/crontabs
          name: crontab


      volumes:
      - name: home
        nfs:
          server: 10.145.254.55
          path: /home/nfsroot/Scrap
          readOnly: false
      - name: crontab
        nfs:
          server: 10.145.254.55
          path: /home/nfsroot/Scrap/cron
          readOnly: false
