apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-webui
  labels:
    app: open-webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-webui
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: open-webui
    spec:
      # volumes:
      #   - name: volume-fhg88u
      #     persistentVolumeClaim:
      #       claimName: openwebui

      containers:
        - name: container-kaxnqv
          image: '10.3.18.60/docker/open-webui:0.5.7'
          ports:
            - name: http-0
              containerPort: 8080
              protocol: TCP
          env:
            - name: OLLAMA_BASE_URL
              value: 'http://10.3.68.3:11434'
            - name: WEBUI_SECRET_KEY
              value: test
            - name: HF_ENDPOINT
              value: 'https://hf-mirror.com'
          resources: {}
          volumeMounts:
            - name: openwebui-data
              mountPath: /app/backend/data
          # imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/hostname: node-96.k8s.tsdc.io

      volumes:
      - name: openwebui-data
        nfs:
          server: 10.145.254.55
          path: /home/nfsroot/openwebui
          readOnly: false    
---
apiVersion: v1
kind: Service
metadata:
  name: open-webui
  labels:
    app: open-webui
spec:
  type: ClusterIP
  clusterIP: 10.18.1.6
  ports:
    - name: http-0
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: open-webui

---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: openwebui
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 10Gi
