apiVersion: apps/v1
kind: Deployment
metadata:
  name: tdx-crawler-deployment
spec:
  selector:
    matchLabels:
      app: tdx-crawler
  replicas: 1 # 告知 Deployment 运行 2 个与该模板匹配的 Pod
  template:
    metadata:
      labels:
        app: tdx-crawler
    spec:
      containers:
      - name: tdx-crawler
        image: 10.3.18.60/docker/tdx-crawler:v1
