apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-server-deployment
spec:
  selector:
    matchLabels:
      app: zabbix-server
  replicas: 1 # 告知 Deployment 运行 2 个与该模板匹配的 Pod
  template:
    metadata:
      labels:
        app: zabbix-server
    spec:
      containers:
      - name: zabbix-server
        image: 10.3.18.60/docker/zabbix-server-pgsql:latest
        env:
          - name: ZBX_ALLOWUNSUPPORTEDDBVERSIONS
            value: "1"
          - name: DB_SERVER_HOST
            value: "10.3.18.59"
          - name: POSTGRES_USER
            value: 'sa'
          - name:  POSTGRES_PASSWORD
            value: '11111111'
          # - name: PGADMIN_CONFIG_LOGIN_BANNER
          #   value: "Authorised users only!"
          # - name: PGADMIN_CONFIG_CONSOLE_LOG_LEVEL
          #   value: '10'
        ports:
          - containerPort: 10051
---
apiVersion: v1
kind: Service
metadata:
   name: zabbix-server-svc
   namespace: default
spec:
   type: ClusterIP
   clusterIP: 10.88.2.2
   selector:
      app: zabbix-server
   ports:
   - name: zabbix-server-http
     protocol: TCP
     port: 10051
     targetPort: 10051
