[uwsgi]
uid = ts
master = true


socket = 0.0.0.0:3031
buffer-size = 4096
#chmod-socket = 755
socket-timeout = 3
processes = 2
cacuum = true
thunder-lock = true
enable-threads = true
pidfile = uwsgi.pid
daemonize = /tmp/uwsgi.log
#logto = /home/ts/app/www/uwsgi/uwsgi.log

chdir = /home/ts/app/www/
wsgi-file = app.py
callable=app
