[uwsgi]
uid = root
master = true

socket = :3031
chmod-socket = 755
socket-timeout = 3
processes = 2
cacuum = true
thunder-lock = true
enable-threads = true
pidfile = /home/uwsgi.pid
; daemonize = /tmp/uwsgi.log
#logto = /home/ts/app/www/uwsgi/uwsgi.log


chdir = /home
wsgi-file = www.py
callable=app
