output:
  dir: "output"
  subdirs:
    html: "html"
    excel: "excel"
    images: "images"

logging:
  level: "INFO"
  format: "%(asctime)s [%(levelname)s] %(message)s"

visual:
  default_height: 1800
  default_width: 1600
  sankey_node_pad: 15
  sankey_node_thickness: 20