# V7 数据获取测试 Notebook

本 notebook 系统测试 V7 系统所有数据源的数据获取能力，覆盖：

| 数据源 | 类型 | 测试内容 |
|--------|------|----------|
| TDX 标准连接 | 指数/股票 | 沪深300、中证500 等 |
| TDX 扩展连接 | 期货/期权 | IF/IH/IC/IM、商品期货 |
| PostgreSQL tdxIndex | 合约映射 | 历史数据回退 |
| PostgreSQL csiIndexPE | PE/PB | 估值百分位数据 |
| AKShare | 外盘期货 | WTI、COMEX黄金等 |
| pytdx 直连 | 期权PCR | 真实PCR数据 |
| 动态合约推导 | ContractManager | 近月/远月/期权合约 |


In [1]:
import sys, os
from pathlib import Path

# 设置项目根目录
PROJECT_ROOT = Path().resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))
print(f'项目根目录: {PROJECT_ROOT}')

import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import warnings
warnings.filterwarnings('ignore')

pd.set_option('display.max_columns', 30)
pd.set_option('display.width', 120)
pd.set_option('display.float_format', '{:.4f}'.format)

print(f'pandas={pd.__version__}, numpy={np.__version__}')
print(f'当前时间: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}')

项目根目录: /home/ts/app/AiStock
pandas=3.0.2, numpy=2.3.5
当前时间: 2026-05-22 14:15:13


In [2]:
# 加载 V7 系统配置
import yaml

config_path = PROJECT_ROOT / 'config'  / 'markete_state' /'system_config.yaml'
if config_path.exists():
    with open(config_path, 'r', encoding='utf-8') as f:
        config = yaml.safe_load(f)
    print(f'✅ 配置加载成功: {config_path}')
    print(f'  系统版本: {config.get("system", {}).get("version")}')
    print(f'  TDX标准: {config.get("tdx", {}).get("hq_host")}:{config.get("tdx", {}).get("hq_port")}')
    print(f'  TDX扩展: {config.get("tdx", {}).get("exhq_host")}:{config.get("tdx", {}).get("exhq_port")}')
else:
    print(f'⚠️ 配置文件不存在: {config_path}')
    config = {}

✅ 配置加载成功: /home/ts/app/AiStock/config/markete_state/system_config.yaml
  系统版本: 7.0.0
  TDX标准: 180.153.18.170:7709
  TDX扩展: 47.112.95.207:7720


## 1. TDX 标准连接测试（指数/股票）

TDX 标准连接 (hq_host:180.153.18.170:7709) 用于获取 A股/指数数据

In [3]:
# 初始化 TDXAdapter — 标准连接
from data_services.tdx_adapter import TDXAdapter

tdx_standard = TDXAdapter({
    'host': config.get('tdx', {}).get('hq_host', '180.153.18.170'),
    'port': config.get('tdx', {}).get('hq_port', 7709),
    'pool_size': 3,
    'retry_count': 2,
})
print(f'TDX 标准连接状态: {"✅可用" if tdx_standard.is_available() else "❌不可用"}')
print(repr(tdx_standard))

TDX 标准连接状态: ✅可用


In [4]:
tdx_standard.get_bars('000905','index_zz', days=200)

,datetime,open,high,low,close,volume,turnover,open_interest
0,2025-07-23 15:00:00,6218.2070,6256.1514,6187.0122,6196.7578,2,311060.2188,1217913479
1,2025-07-24 15:00:00,6197.8530,6293.5986,6197.8530,6293.5986,268,320187.9688,1218205567
2,2025-07-25 15:00:00,6297.6255,6311.1685,6276.4155,6299.5908,237,304368.0625,1217699330
3,2025-07-28 15:00:00,6305.2246,6329.0303,6271.9302,6323.4199,214,305210.0938,1217726275
4,2025-07-29 15:00:00,6308.1226,6356.1499,6272.3140,6356.1328,201,292526.9062,1217320413
...,...,...,...,...,...,...,...,...
195,2026-05-18 15:00:00,8493.0156,8606.4092,8472.4248,8554.2373,231,559260.8750,1225296334
196,2026-05-19 15:00:00,8524.1543,8633.0615,8416.5146,8627.9463,243,571307.0000,1225489072
197,2026-05-20 15:00:00,8581.3936,8681.7227,8552.4277,8656.3066,230,574479.5000,1225539832
198,2026-05-21 15:00:00,8703.1738,8790.3750,8406.2881,8419.8369,279,687607.6875,1227349883


In [5]:
tdx_standard.get_bars('000905','index_sh', days=200)

,datetime,open,high,low,close,volume,turnover
0,2025-07-23 15:00:00,6218.2100,6256.1500,6187.0100,6196.7600,2583779.0000,311060234240.0000
1,2025-07-24 15:00:00,6197.8500,6293.6000,6197.8500,6293.6000,2683555.0000,320187957248.0000
2,2025-07-25 15:00:00,6297.6300,6311.1700,6276.4200,6299.5900,2370553.0000,304368058368.0000
3,2025-07-28 15:00:00,6305.2200,6329.0300,6271.9300,6323.4200,2144482.0000,305210097664.0000
4,2025-07-29 15:00:00,6308.1200,6356.1500,6272.3100,6356.1300,2017576.0000,292526915584.0000
...,...,...,...,...,...,...,...
195,2026-05-18 15:00:00,8493.0210,8606.4120,8472.4210,8554.2420,2310934.0000,559260893184.0000
196,2026-05-19 15:00:00,8524.1520,8633.0610,8416.5210,8627.9520,2438688.0000,571306999808.0000
197,2026-05-20 15:00:00,8581.3910,8681.7210,8552.4310,8656.3110,2304187.0000,574479532032.0000
198,2026-05-21 15:00:00,8703.1710,8790.3810,8406.2910,8419.8410,2794891.0000,687607709696.0000


In [6]:
# 测试获取指数数据 — 沪深300
if tdx_standard.is_available():
    df_hs300 = tdx_standard.get_bars('000300', 'index_sh', days=500)
    if df_hs300 is not None and len(df_hs300) > 0:
        print(f'✅ 沪深300 数据获取成功: {len(df_hs300)} 条')
        print(f'  日期范围: {df_hs300["datetime"].min()} ~ {df_hs300["datetime"].max()}')
        print(f'  列名: {list(df_hs300.columns)}')
        display(df_hs300.tail(5))
    else:
        print('❌ 沪深300 数据获取失败')
else:
    print('⚠️ TDX 标准连接不可用，跳过')

✅ 沪深300 数据获取成功: 500 条
  日期范围: 2024-04-26 15:00:00 ~ 2026-05-22 15:00:00
  列名: ['datetime', 'open', 'high', 'low', 'close', 'volume', 'turnover']


,datetime,open,high,low,close,volume,turnover
495,2026-05-18 15:00:00,4836.3300,4868.6000,4806.1500,4833.5200,2390775.0000,733452828672.0000
496,2026-05-19 15:00:00,4818.7100,4854.5200,4773.5300,4852.8800,2322808.0000,712401027072.0000
497,2026-05-20 15:00:00,4829.6100,4866.2100,4825.6400,4850.7000,2200232.0000,729653313536.0000
498,2026-05-21 15:00:00,4886.2400,4937.9300,4780.7100,4783.1000,2873425.0000,891936374784.0000
499,2026-05-22 15:00:00,4818.8430,4851.3490,4785.3480,4844.1440,2463948.0000,654231732224.0000


In [7]:
# 测试获取中证500、中证1000、中证2000
test_indices = {
    '000300': ('沪深300', 'index_sh'),
    '000905': ('中证500', 'index_zz'),
    '000852': ('中证1000', 'index_zz'),
    '932000': ('中证2000', 'index_zz'),
}

index_results = {}
if tdx_standard.is_available():
    for code, (name, mtype) in test_indices.items():
        df = tdx_standard.get_bars(code, mtype, days=60)
        if df is not None and len(df) > 0:
            index_results[name] = {'code': code, 'rows': len(df), 'latest': df['close'].iloc[-1]}
            print(f'✅ {name}({code}): {len(df)}条 | 最新收盘={df["close"].iloc[-1]:.2f}')
        else:
            print(f'❌ {name}({code}): 获取失败')
else:
    print('⚠️ TDX 不可用')

pd.DataFrame(index_results).T if index_results else print('无结果')

✅ 沪深300(000300): 60条 | 最新收盘=4843.93
✅ 中证500(000905): 60条 | 最新收盘=8575.76
✅ 中证1000(000852): 60条 | 最新收盘=8700.40
✅ 中证2000(932000): 60条 | 最新收盘=3664.13


,code,rows,latest
沪深300,000300,60,4843.9260
中证500,000905,60,8575.7607
中证1000,000852,60,8700.3975
中证2000,932000,60,3664.1321


## 2. TDX 扩展连接测试（期货/期权）

TDX 扩展连接 (exhq_host:47.112.95.207:7720) 用于获取期货、期权等衍生品数据

In [8]:
# 初始化 TDXAdapter — 扩展连接
tdx_extended = TDXAdapter({
    'host': config.get('tdx', {}).get('exhq_host', '47.112.95.207'),
    'port': config.get('tdx', {}).get('exhq_port', 7720),
    'pool_size': 3,
    'retry_count': 2,
})
print(f'TDX 扩展连接状态: {"✅可用" if tdx_extended.is_available() else "❌不可用"}')
print(repr(tdx_extended))

TDX 扩展连接状态: ✅可用


In [9]:
tdx_extended.get_bars('APL8','future_zz', days=200)

,datetime,open,high,low,close,volume,turnover,open_interest
0,2025-07-23 15:00:00,7929.0000,7988.0000,7909.0000,7956.0000,7356,0.0000,91030
1,2025-07-24 15:00:00,7938.0000,8014.0000,7921.0000,7969.0000,333,0.0000,93548
2,2025-07-25 15:00:00,7990.0000,8023.0000,7964.0000,8005.0000,345,0.0000,94831
3,2025-07-28 15:00:00,7979.0000,8437.0000,7924.0000,8052.0000,2494,0.0000,127261
4,2025-07-29 15:00:00,8050.0000,8060.0000,7868.0000,7908.0000,947,0.0000,103588
...,...,...,...,...,...,...,...,...
195,2026-05-18 15:00:00,7652.0000,7658.0000,7370.0000,7428.0000,2231,0.0000,136927
196,2026-05-19 15:00:00,7420.0000,7455.0000,7356.0000,7390.0000,835,0.0000,123202
197,2026-05-20 15:00:00,7398.0000,7428.0000,7347.0000,7393.0000,615,0.0000,122218
198,2026-05-21 15:00:00,7383.0000,7547.0000,7383.0000,7490.0000,1243,0.0000,118172


In [50]:
# 测试获取股指期货数据
from market_state_system.core.contract_manager import ContractManager

cm = ContractManager(reference_date=datetime.now())
idx_futures = cm.get_index_futures_contracts()

futures_results = {}
if tdx_extended.is_available():
    for key, contract in idx_futures.items():
        # 先尝试主力合约(主连)
        main_code = cm.get_index_futures_main_code(key)
        df = tdx_extended.get_bars(main_code, 'future_zj', days=60)
        if df is not None and len(df) > 0:
            futures_results[key] = {
                'main_code': main_code,
                'active_code': contract.futures_code,
                'rows': len(df),
                'latest_close': df['close'].iloc[-1],
            }
            print(f'✅ {key.upper()}({main_code}): {len(df)}条 | 收盘={df["close"].iloc[-1]:.2f}')
        else:
            print(f'❌ {key.upper()}({main_code}): 获取失败')
else:
    print('⚠️ TDX 扩展连接不可用')

pd.DataFrame(futures_results).T if futures_results else print('无结果')

✅ IF(IFL8): 60条 | 收盘=4788.20
✅ IH(IHL8): 60条 | 收盘=2899.20
✅ IC(ICL8): 60条 | 收盘=8469.20
✅ IM(IML8): 60条 | 收盘=8589.80


,main_code,active_code,rows,latest_close
if,IFL8,IF2606,60,4788.2002
ih,IHL8,IH2606,60,2899.2000
ic,ICL8,IC2606,60,8469.2002
im,IML8,IM2606,60,8589.7998


In [ ]:
mgr = ContractManager(
    # code_table_path=code_table,
    reference_date=datetime.now(),
)
# 1. 商品期货合约
print("\n1. 商品期货合约（动态推导）:")
pairs = mgr.get_commodity_contracts()
for key, pair in pairs.items():
    print(
        f"  {key:10s}: 近月={pair.near_code}({pair.near_year}-{pair.near_month:02d}) "
        f"远月={pair.far_code}({pair.far_year}-{pair.far_month:02d}) "
        f"market_type={pair.market_type}"
    )

# 2. 股指期货合约
print("\n2. 股指期货合约（动态推导）:")
idx = mgr.get_index_futures_contracts()
for key, contract in idx.items():
    main = mgr.get_index_futures_main_code(key)
    print(
        f"  {key:4s}: 当月={contract.futures_code} 主连={main} "
        f"下季月={contract.next_quarter_code} 现货={contract.spot_code} "
        f"market_type={contract.market_type}"
    )

# 3. 动态配置
print("\n3. 生成的动态配置:")
config = mgr.generate_full_config_updates()
for k, v in config.items():
    if isinstance(v, dict):
        print(f"  {k}:")
        for kk, vv in list(v.items())[:3]:
            print(f"    {kk}: {vv}")
        if len(v) > 3:
            print(f"    ... ({len(v)} items)")
    else:
        print(f"  {k}: {v}")

# 4. 合约摘要
print("\n4. 合约推导摘要:")
summary = mgr.get_contract_summary()
print(summary.to_string(index=False))

# 5. 到期检查
print("\n5. 到期预警:")
expiry_warnings = mgr.check_expiry_warnings()
if expiry_warnings:
    for w in expiry_warnings:
        print(f"  WARNING: {w['warning']}")
else:
    print("  无即将到期的合约")

# 6. 品种信息查询
print("\n6. 品种信息查询（示例）:")
for v in ['CU', 'AU', 'LC', 'M', 'IF']:
    info = mgr.get_variety_info(v)
    if info:
        print(
            f"  {v}: {info['name']} | market_type={info['market_type']} | "
            f"delivery_months={info['delivery_months']}"
        )

print("\n" + "=" * 80)
print("测试完成")

In [13]:
# 测试获取商品期货数据
commodity_results = {}
if tdx_extended.is_available():
    commodity_pairs = cm.get_commodity_contracts()
    for key, pair in commodity_pairs.items():
        # 尝试主力合约(主连)
        main_code = f'{pair.variety_code}L8'
        df = tdx_extended.get_bars(main_code, pair.market_type, days=30)
        if df is not None and len(df) > 0:
            commodity_results[key] = {
                'variety': pair.variety_code,
                'main_code': main_code,
                'near_code': pair.near_code,
                'far_code': pair.far_code,
                'market_type': pair.market_type,
                'rows': len(df),
                'latest_close': df['close'].iloc[-1],
            }
            print(f'✅ {key}({main_code}): {len(df)}条 | 收盘={df["close"].iloc[-1]:.2f}')
        else:
            print(f'❌ {key}({main_code}): 获取失败')
else:
    print('⚠️ TDX 扩展连接不可用')

pd.DataFrame(commodity_results).T if commodity_results else print('无结果')

✅ copper(CUL8): 30条 | 收盘=105000.00
✅ aluminum(ALL8): 30条 | 收盘=24525.00
✅ lithium(LCL8): 30条 | 收盘=183780.00
✅ silicon(SIL8): 30条 | 收盘=8450.00
✅ crude(SCL8): 30条 | 收盘=639.80
✅ rebar(RBL8): 30条 | 收盘=3169.00
✅ gold(AUL8): 30条 | 收盘=992.18
✅ soybean(ML8): 30条 | 收盘=2986.00


,variety,main_code,near_code,far_code,market_type,rows,latest_close
copper,CU,CUL8,CU2606,CU2607,future_sh,30,105000.0000
aluminum,AL,ALL8,AL2606,AL2607,future_sh,30,24525.0000
lithium,LC,LCL8,LC2606,LC2607,future_gz,30,183780.0000
silicon,SI,SIL8,SI2606,SI2607,future_gz,30,8450.0000
crude,SC,SCL8,SC2606,SC2607,future_sh,30,639.8000
rebar,RB,RBL8,RB2606,RB2607,future_sh,30,3169.0000
gold,AU,AUL8,AU2606,AU2608,future_sh,30,992.1800
soybean,M,ML8,M2607,M2608,future_dl,30,2986.0000


## 3. 期权 PCR 数据测试（pytdx 直连）

V7 核心改进：使用 pytdx 直连扩展行情获取真实期权持仓量数据，
而非 V6 的随机数伪造。PCR (Put-Call Ratio) = 看跌持仓量 / 看涨持仓量

In [25]:
tdxAPIcode = db_reader.read_table('tdxAPIcode',engine_name='index_db')

In [32]:
tdxAPIcode[tdxAPIcode.market_code==7]

,code,code_name,category,market_code,market_name
17010,HO8U03PD,HO2606-C-2400,12,7,中金所期权
17011,HO8U03S5,HO2606-C-2450,12,7,中金所期权
17012,HO8U03UX,HO2606-C-2500,12,7,中金所期权
17013,HO8U03XP,HO2606-C-2550,12,7,中金所期权
17014,HO8U040H,HO2606-C-2600,12,7,中金所期权
...,...,...,...,...,...
17705,MO930DW0,MO2703-P-9000,12,7,中金所期权
17706,MO930E74,MO2703-P-9200,12,7,中金所期权
17707,MO930EI8,MO2703-P-9400,12,7,中金所期权
17708,MO930ETC,MO2703-P-9600,12,7,中金所期权


In [53]:
import pandas as pd

def fetch_option_pcr_simple(tdx_adapter, tdxAPIcode, underlying='IO', market_code=8, near_month=None):
    """
    简化版期权PCR获取：
    1. 从 tdxAPIcode 数据框中获取指定标的的期权合约列表
    2. 获取每个合约的日线数据(含持仓量)
    3. 按看涨/看跌分类，计算PCR
    
    Args:
        tdx_adapter: TDXAdapter实例(扩展连接)
        tdxAPIcode: pandas.DataFrame, 证券列表数据框 (需包含 market_code, code, code_name/name 列)
        underlying: 标的代码，如 'IO', 'MO', '510300'
        market_code: TDX市场代码 (如 7 为 ETF期权, 30 为中金所期权)
        near_month: 近月合约月份(YYYYMM 或 YYMM)，如 '202606' 或 '2606'
    """
    if not tdx_adapter.is_available():
        return None
        
    if tdxAPIcode is None or not isinstance(tdxAPIcode, pd.DataFrame) or tdxAPIcode.empty:
        print("❌ tdxAPIcode 数据框为空、未定义或类型错误")
        return None

    try:
        # 【修正1】动态识别名称列名（兼容 'code_name' 或 'name'）
        name_col = 'code_name' if 'code_name' in tdxAPIcode.columns else 'name'
        if name_col not in tdxAPIcode.columns:
            print("❌ tdxAPIcode 中缺少 'code_name' 或 'name' 列")
            return None

        # 【修正2】利用 Pandas 向量化操作进行高效过滤，替代低效的循环
        mask = (tdxAPIcode['market_code'] == market_code)
        
        if underlying in ['IO', 'MO']:
            mask &= (tdxAPIcode['code'].str.startswith(underlying, na=False) | 
                     tdxAPIcode[name_col].str.startswith(underlying, na=False))
        else:
            mask &= (tdxAPIcode['code'].str.contains(underlying, na=False) | 
                     tdxAPIcode[name_col].str.contains(underlying, na=False))
                     
        df_options = tdxAPIcode[mask]
        
        # 【修正3】使用 orient='records' 确保输出结构为 [{col: val}, ...]，并统一列名为 'name'
        all_options = df_options[['code', name_col]].rename(columns={name_col: 'name'}).to_dict(orient='records')
        
        # 【修正4】应用 near_month 过滤（在转换为字典后处理，逻辑更清晰）
        if near_month:
            month_str = str(near_month)
            short_month = month_str[2:] if len(month_str) == 6 else month_str
            
            all_options = [
                opt for opt in all_options 
                if (month_str in opt['code'] or month_str in opt['name'] or 
                    short_month in opt['code'] or short_month in opt['name'])
            ]

        # 分类看涨/看跌
        calls = []
        puts = []
        for o in all_options:
            code = o['code']
            name = o['name']
            
            if 'C' in code or '购' in name or '-C-' in name or 'C3' in name or 'C4' in name:
                calls.append(o)
            elif 'P' in code or '沽' in name or '-P-' in name or 'P3' in name or 'P4' in name:
                puts.append(o)
                
        print(f'  {underlying} 期权合约: 总={len(all_options)}, 看涨={len(calls)}, 看跌={len(puts)}')
        
        if not calls or not puts:
            print(f'  ⚠️ 未找到足够的看涨或看跌合约，无法计算PCR')
            return None

        # 获取看涨持仓量总和（已移除原代码中导致数据失真的 [:20] 截断）
        call_oi = 0.0
        for opt in calls:
            df = tdx_adapter.get_bars(opt['code'], 'option_zj', days=1)
            if df is not None and len(df) > 0 and 'open_interest' in df.columns:
                call_oi += float(df['open_interest'].iloc[-1])
        
        # 获取看跌持仓量总和
        put_oi = 0.0
        for opt in puts:
            df = tdx_adapter.get_bars(opt['code'], 'option_zj', days=1)
            if df is not None and len(df) > 0 and 'open_interest' in df.columns:
                put_oi += float(df['open_interest'].iloc[-1])
        
        pcr = put_oi / call_oi if call_oi > 0 else None
        
        return {
            'underlying': underlying,
            'total_options': len(all_options),
            'call_count': len(calls),
            'put_count': len(puts),
            'call_oi': round(call_oi, 2),
            'put_oi': round(put_oi, 2),
            'pcr': round(pcr, 4) if pcr else None,
        }
    except Exception as e:
        print(f'❌ PCR获取异常: {e}')
        import traceback
        traceback.print_exc()
        return None

print('期权PCR获取函数已定义')

期权PCR获取函数已定义


In [54]:
# 执行PCR数据获取测试
if tdx_extended.is_available():
    pcr_result = fetch_option_pcr_simple(tdx_extended,tdxAPIcode, underlying='510300')
    if pcr_result:
        print(f'\n✅ IO(沪深300)期权PCR数据:')
        print(f'  合约总数: {pcr_result["total_options"]}')
        print(f'  看涨合约: {pcr_result["call_count"]}')
        print(f'  看跌合约: {pcr_result["put_count"]}')
        print(f'  看涨持仓量: {pcr_result["call_oi"]:.0f}')
        print(f'  看跌持仓量: {pcr_result["put_oi"]:.0f}')
        print(f'  PCR(看跌/看涨): {pcr_result["pcr"]}')
    else:
        print('❌ PCR获取失败')
else:
    print('⚠️ TDX 扩展连接不可用，跳过PCR测试')

  510300 期权合约: 总=136, 看涨=0, 看跌=0
  ⚠️ 未找到足够的看涨或看跌合约，无法计算PCR
❌ PCR获取失败


## 4. PostgreSQL 数据库测试

V7 使用两个 PostgreSQL 数据库：
- `tdxIndex` (10.3.18.56): 指数历史数据、合约映射
- `csiIndexPE`: PE/PB 估值数据

In [21]:
# 初始化 DatabaseReader
from data_services.database_reader import DatabaseReader
from config.global_settings import DATABASE_ENGINES, DB_POOL_CONFIG

print('数据库配置:')
for name, url in DATABASE_ENGINES.items():
    # 隐藏密码
    safe_url = url.split('@')[0].rsplit(':', 1)[0] + ':***@' + url.split('@')[-1] if '@' in url else url
    print(f'  {name}: {safe_url}')

db_reader = DatabaseReader(DATABASE_ENGINES, DB_POOL_CONFIG)
print(f'\nDatabaseReader 初始化完成, 引擎数: {len(db_reader._engines)}')

数据库配置:
  index_db: postgresql+psycopg://sa:***@10.3.18.56/tdxIndex
  stock_db: postgresql+psycopg://sa:***@10.3.18.56/tdxStocks
  stock_base_db: postgresql+psycopg://sa:***@10.3.18.56/StockBas
  stock_fs_db: postgresql+psycopg://sa:***@10.3.18.56/tdxFS
  index_pe_db: postgresql+psycopg://sa:***@10.3.18.56/csiIndexPE

DatabaseReader 初始化完成, 引擎数: 5


In [24]:
db_reader.read_table('tdxAPIcode',engine_name='index_db')

,code,code_name,category,market_code,market_name
0,00001,长和,2,71,港股通
1,00002,中电控股,2,71,港股通
2,00003,香港中华煤气,2,71,港股通
3,00004,九龙仓集团,2,71,港股通
4,00005,汇丰控股,2,71,港股通
...,...,...,...,...,...
79148,988006,CNTHKD,5,102,国证指数
79149,988007,CNTUSD,5,102,国证指数
79150,988106,CNTTRHKD,5,102,国证指数
79151,988107,CNTTRUSD,5,102,国证指数


In [22]:
# 测试 tdxIndex 数据库
print('=== tdxIndex 数据库健康检查 ===')
try:
    is_healthy = db_reader.health_check('index_db')
    print(f'  健康状态: {"✅" if is_healthy else "❌"}')
    
    if is_healthy:
        # 尝试读取沪深300数据
        df_db = db_reader.read_table('000300', engine_name='index_db',
                                     order_by='datetime DESC', limit=5,
                                     parse_dates=['datetime'])
        if not df_db.empty:
            print(f'  ✅ 沪深300数据: {len(df_db)}条')
            display(df_db.head())
        else:
            print('  ⚠️ 无数据返回')
except Exception as e:
    print(f'❌ tdxIndex测试失败: {e}')

=== tdxIndex 数据库健康检查 ===
  健康状态: ✅
  ✅ 沪深300数据: 5条


,datetime,open,close,high,low,vol,amount,year,month,day,hour,minute,up_count,down_count
0,2026-05-21 15:00:00,4886.2400,4783.1000,4937.9300,4780.7100,2873425.0000,891936374784.0000,2026,5,21,15,0,72,221
1,2026-05-20 15:00:00,4829.6100,4850.7000,4866.2100,4825.6400,2200232.0000,729653313536.0000,2026,5,20,15,0,89,210
2,2026-05-19 15:00:00,4818.7100,4852.8800,4854.5200,4773.5300,2322808.0000,712401027072.0000,2026,5,19,15,0,187,107
3,2026-05-18 15:00:00,4836.3300,4833.5200,4868.6000,4806.1500,2390775.0000,733452828672.0000,2026,5,18,15,0,91,203
4,2026-05-15 15:00:00,4911.6200,4859.5900,4935.6200,4832.6900,2769677.0000,887687413760.0000,2026,5,15,15,0,63,231


In [23]:
# 测试 csiIndexPE 数据库
print('=== csiIndexPE 数据库健康检查 ===')
try:
    is_healthy = db_reader.health_check('index_pe_db')
    print(f'  健康状态: {"✅" if is_healthy else "❌"}')
    
    if is_healthy:
        # 尝试读取沪深300 PE数据
        df_pe = db_reader.read_table('000300', engine_name='index_pe_db',
                                     order_by='date DESC', limit=5,
                                     parse_dates=['date'])
        if not df_pe.empty:
            print(f'  ✅ 沪深300 PE数据: {len(df_pe)}条')
            print(f'  列名: {list(df_pe.columns)}')
            display(df_pe.head())
        else:
            print('  ⚠️ 无PE数据返回')
except Exception as e:
    print(f'❌ csiIndexPE测试失败: {e}')

=== csiIndexPE 数据库健康检查 ===
  健康状态: ✅


❌ 未知错误 [index_pe_db]: Execution failed on sql '
            SELECT * FROM "000300"
            
            ORDER BY date DESC
            LIMIT 5
        ': (psycopg.errors.UndefinedColumn) column "date" does not exist
LINE 4:             ORDER BY date DESC
                             ^
[SQL: 
            SELECT * FROM "000300"
            
            ORDER BY date DESC
            LIMIT 5
        ]
(Background on this error at: https://sqlalche.me/e/20/f405)


  ⚠️ 无PE数据返回


## 5. AKShare 外盘数据测试

AKShare 适配器用于获取外盘期货、汇率等数据

In [ ]:
# 初始化 AKAdapter
from data_service.ak_adapter import AKAdapter

ak = AKAdapter({'cache_enabled': True, 'cache_ttl': 300})
print(f'AKAdapter 状态: {"✅可用" if ak.is_available() else "❌不可用"}')
print(repr(ak))

In [ ]:
# 测试外盘期货数据
test_symbols = ['CL', 'GC', 'SI', 'DX']  # WTI原油、COMEX黄金、COMEX白银、美元指数

ak_results = {}
if ak.is_available():
    for symbol in test_symbols:
        result = ak.get_futures_realtime(symbol)
        if result:
            ak_results[symbol] = result
            print(f'✅ {symbol}({result["name"]}): 价格={result["price"]} {result.get("price_unit", "")} 涨跌={result.get("change_pct", 0):+.2f}%')
        else:
            print(f'❌ {symbol}: 获取失败')
else:
    print('⚠️ AKShare 不可用')

pd.DataFrame(ak_results).T if ak_results else print('无结果')

## 6. ContractManager 动态合约推导测试

V7 核心改进：基于当前日期动态推导期货/期权合约代码，零硬编码

In [ ]:
# 初始化 ContractManager
code_table_path = str(PROJECT_ROOT / 'data' / 'tdx_code_table.xlsx')
cm = ContractManager(
    code_table_path=code_table_path if os.path.exists(code_table_path) else None,
    reference_date=datetime.now(),
    rollover_day=config.get('contract_manager', {}).get('rollover_day', 15),
)
print(f'ContractManager 初始化完成')
print(f'  参考日期: {cm.reference_date.strftime("%Y-%m-%d")}')
print(f'  滚动日: 每月{cm.rollover_day}号后切换')
print(f'  已加载合约数: {len(cm._code_table)}')

In [ ]:
# 测试商品期货合约推导
commodity_pairs = cm.get_commodity_contracts()
print(f'商品期货合约推导结果 ({len(commodity_pairs)}个品种):')
print(f'{"品种":<12} {"代码":<6} {"近月合约":<10} {"远月合约":<10} {"近月交割":<12} {"市场类型"}')
print('-' * 70)
for key, pair in commodity_pairs.items():
    print(f'{key:<12} {pair.variety_code:<6} {pair.near_code:<10} {pair.far_code:<10} '
          f'{pair.near_year}-{pair.near_month:02d}/{pair.far_year}-{pair.far_month:02d}  {pair.market_type}')

In [ ]:
# 测试股指期货合约推导
idx_futures = cm.get_index_futures_contracts()
print(f'股指期货合约推导结果:')
print(f'{"品种":<6} {"当月合约":<10} {"下季月合约":<12} {"现货代码":<10} {"交割月"}')
print('-' * 55)
for key, contract in idx_futures.items():
    print(f'{key.upper():<6} {contract.futures_code:<10} {contract.next_quarter_code:<12} '
          f'{contract.spot_code:<10} {contract.delivery_year}-{contract.delivery_month:02d}')

In [ ]:
# 测试期权近月推导
option_underlyings = ['IO', 'MO', '510300', '588000']
print(f'期权近月交割推导:')
for underlying in option_underlyings:
    near_year, near_month = cm.get_option_near_month(underlying)
    print(f'  {underlying}: 近月 = {near_year}年{near_month}月')

## 7. DataLoadingService 集成测试

测试统一数据加载服务，验证 TDX → DB 降级逻辑

In [ ]:
# 初始化完整数据服务
from base_services.config_service import ConfigService
from base_services.cache_service import CacheService
from data_service.data_loader_service import DataLoadingService

# 简易配置服务
cfg_svc = ConfigService(system_name='market_state_system', enable_hot_reload=False)

# 初始化 DataLoadingService
data_svc = DataLoadingService(
    config_service=cfg_svc,
    database_reader=db_reader,
    tdx_adapter=tdx_standard,  # 标准连接
    ak_adapter=ak,
    cache_service=CacheService(max_size=100, ttl=3600),
    enable_cache=True,
)
print(f'DataLoadingService 初始化完成')

In [ ]:
# 测试各类数据加载
print('=== DataLoadingService 集成测试 ===\n')

# 1. 指数数据
df_idx = data_svc.load_index_data('000300', min_days=60)
print(f'1. 沪深300指数: {"✅" if len(df_idx) > 0 else "❌"} {len(df_idx)}条')

# 2. 衍生品数据
df_deriv = data_svc.load_derivative_data('IFL8', 'future_zj', days=30)
print(f'2. IF主连期货: {"✅" if len(df_deriv) > 0 else "❌"} {len(df_deriv)}条')

# 3. PE数据
df_pe = data_svc.load_pe_data('000300')
print(f'3. 沪深300 PE: {"✅" if len(df_pe) > 0 else "❌"} {len(df_pe)}条')

# 4. 宏观数据
macro_results = data_svc.load_all_macro_indicators()
print(f'4. 宏观指标: {len(macro_results)}个指标')
for k, v in macro_results.items():
    print(f'   {k}: {v}')

# 缓存统计
stats = data_svc.get_cache_stats()
print(f'\n缓存统计: 命中率={stats["hit_rate"]:.1%} | 使用={stats["size"]}')

## 8. 数据获取能力汇总

汇总所有数据源的可用性和数据质量

In [ ]:
# 数据获取能力汇总
summary = {
    '数据源': [],
    '类型': [],
    '状态': [],
    '数据量': [],
    '备注': [],
}

# TDX标准
summary['数据源'].append('TDX标准(7709)')
summary['类型'].append('指数/股票')
summary['状态'].append('✅' if tdx_standard.is_available() else '❌')
summary['数据量'].append(f'{len(df_idx)}条' if len(df_idx) > 0 else '0')
summary['备注'].append('沪深300等指数数据')

# TDX扩展
summary['数据源'].append('TDX扩展(7720)')
summary['类型'].append('期货/期权')
summary['状态'].append('✅' if tdx_extended.is_available() else '❌')
summary['数据量'].append(f'{len(futures_results)}品种' if futures_results else '0')
summary['备注'].append('IF/IH/IC/IM + 商品期货')

# PostgreSQL tdxIndex
summary['数据源'].append('PostgreSQL tdxIndex')
summary['类型'].append('历史数据')
try:
    db_ok = db_reader.health_check('index_db')
except:
    db_ok = False
summary['状态'].append('✅' if db_ok else '❌')
summary['数据量'].append('回退用')
summary['备注'].append('TDX不可用时降级')

# PostgreSQL csiIndexPE
summary['数据源'].append('PostgreSQL csiIndexPE')
summary['类型'].append('PE/PB')
try:
    pe_ok = db_reader.health_check('index_pe_db')
except:
    pe_ok = False
summary['状态'].append('✅' if pe_ok else '❌')
summary['数据量'].append(f'{len(df_pe)}条' if len(df_pe) > 0 else '0')
summary['备注'].append('估值百分位关键数据')

# AKShare
summary['数据源'].append('AKShare')
summary['类型'].append('外盘/汇率')
summary['状态'].append('✅' if ak.is_available() else '❌')
summary['数据量'].append(f'{len(ak_results)}品种' if ak_results else '0')
summary['备注'].append('WTI/黄金/美元指数')

# 期权PCR
summary['数据源'].append('pytdx直连PCR')
summary['类型'].append('期权PCR')
summary['状态'].append('✅' if pcr_result and pcr_result.get('pcr') else '❌')
summary['数据量'].append(f'PCR={pcr_result["pcr"]}' if pcr_result and pcr_result.get('pcr') else 'N/A')
summary['备注'].append('V7核心改进: 真实PCR')

# ContractManager
summary['数据源'].append('ContractManager')
summary['类型'].append('动态合约')
summary['状态'].append('✅')
summary['数据量'].append(f'{len(commodity_pairs)}商品+{len(idx_futures)}股指')
summary['备注'].append('零硬编码日期驱动')

df_summary = pd.DataFrame(summary)
print('V7 数据获取能力汇总:')
display(df_summary)

# 可用率统计
available = sum(1 for s in summary['状态'] if '✅' in s)
total = len(summary['状态'])
print(f'\n数据源可用率: {available}/{total} = {available/total:.0%}')

In [ ]:
# 清理资源
tdx_standard.close()
tdx_extended.close()
db_reader.close()
ak.close()
print('✅ 所有数据源连接已关闭')