#!/usr/bin/env python3
"""Generate V7 test notebooks for data acquisition, core algorithms, and visualization."""

import json
import os

OUTPUT_DIR = "/home/ts/app/AiStock/market_state_system/notebooks"

def make_cell(cell_type, source, metadata=None):
    """Create a notebook cell dict."""
    cell = {
        "cell_type": cell_type,
        "metadata": metadata or {},
        "source": source if isinstance(source, list) else [source],
    }
    if cell_type == "code":
        cell["execution_count"] = None
        cell["outputs"] = []
    return cell

def make_nb(cells, kernel="python3"):
    """Create a notebook dict."""
    return {
        "cells": cells,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": kernel,
            },
            "language_info": {
                "name": "python",
                "version": "3.10.0",
            },
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }

def write_nb(nb, filename):
    path = os.path.join(OUTPUT_DIR, filename)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(nb, f, ensure_ascii=False, indent=1)
    print(f"✅ Written: {path}")

# ══════════════════════════════════════════════════════════════════════════════
# Notebook 1: 数据获取测试
# ══════════════════════════════════════════════════════════════════════════════

nb1_cells = [
    make_cell("markdown", [
        "# V7 数据获取测试 Notebook\n",
        "\n",
        "本 notebook 系统测试 V7 系统所有数据源的数据获取能力，覆盖：\n",
        "\n",
        "| 数据源 | 类型 | 测试内容 |\n",
        "|--------|------|----------|\n",
        "| TDX 标准连接 | 指数/股票 | 沪深300、中证500 等 |\n",
        "| TDX 扩展连接 | 期货/期权 | IF/IH/IC/IM、商品期货 |\n",
        "| PostgreSQL tdxIndex | 合约映射 | 历史数据回退 |\n",
        "| PostgreSQL csiIndexPE | PE/PB | 估值百分位数据 |\n",
        "| AKShare | 外盘期货 | WTI、COMEX黄金等 |\n",
        "| pytdx 直连 | 期权PCR | 真实PCR数据 |\n",
        "| 动态合约推导 | ContractManager | 近月/远月/期权合约 |\n",
    ]),

    # ── Cell 1: 环境初始化 ──
    make_cell("code", [
        "import sys, os\n",
        "from pathlib import Path\n",
        "\n",
        "# 设置项目根目录\n",
        "PROJECT_ROOT = Path().resolve().parent\n",
        "sys.path.insert(0, str(PROJECT_ROOT))\n",
        "print(f'项目根目录: {PROJECT_ROOT}')\n",
        "\n",
        "import pandas as pd\n",
        "import numpy as np\n",
        "from datetime import datetime, timedelta\n",
        "import warnings\n",
        "warnings.filterwarnings('ignore')\n",
        "\n",
        "pd.set_option('display.max_columns', 30)\n",
        "pd.set_option('display.width', 120)\n",
        "pd.set_option('display.float_format', '{:.4f}'.format)\n",
        "\n",
        "print(f'pandas={pd.__version__}, numpy={np.__version__}')\n",
        "print(f'当前时间: {datetime.now().strftime(\"%Y-%m-%d %H:%M:%S\")}')"
    ]),

    # ── Cell 2: 加载配置 ──
    make_cell("code", [
        "# 加载 V7 系统配置\n",
        "import yaml\n",
        "\n",
        "config_path = PROJECT_ROOT / 'config' / 'market_state_system' / 'system_config.yaml'\n",
        "if config_path.exists():\n",
        "    with open(config_path, 'r', encoding='utf-8') as f:\n",
        "        config = yaml.safe_load(f)\n",
        "    print(f'✅ 配置加载成功: {config_path}')\n",
        "    print(f'  系统版本: {config.get(\"system\", {}).get(\"version\")}')\n",
        "    print(f'  TDX标准: {config.get(\"tdx\", {}).get(\"hq_host\")}:{config.get(\"tdx\", {}).get(\"hq_port\")}')\n",
        "    print(f'  TDX扩展: {config.get(\"tdx\", {}).get(\"exhq_host\")}:{config.get(\"tdx\", {}).get(\"exhq_port\")}')\n",
        "else:\n",
        "    print(f'⚠️ 配置文件不存在: {config_path}')\n",
        "    config = {}"
    ]),

    # ── Cell 3: TDX 标准连接测试 ──
    make_cell("markdown", [
        "## 1. TDX 标准连接测试（指数/股票）\n",
        "\n",
        "TDX 标准连接 (hq_host:180.153.18.170:7709) 用于获取 A股/指数数据"
    ]),
    make_cell("code", [
        "# 初始化 TDXAdapter — 标准连接\n",
        "from data_service.tdx_adapter import TDXAdapter\n",
        "\n",
        "tdx_standard = TDXAdapter({\n",
        "    'host': config.get('tdx', {}).get('hq_host', '180.153.18.170'),\n",
        "    'port': config.get('tdx', {}).get('hq_port', 7709),\n",
        "    'pool_size': 3,\n",
        "    'retry_count': 2,\n",
        "})\n",
        "print(f'TDX 标准连接状态: {\"✅可用\" if tdx_standard.is_available() else \"❌不可用\"}')\n",
        "print(repr(tdx_standard))"
    ]),

    make_cell("code", [
        "# 测试获取指数数据 — 沪深300\n",
        "if tdx_standard.is_available():\n",
        "    df_hs300 = tdx_standard.get_index_daily('000300', 'index_sh', days=500)\n",
        "    if df_hs300 is not None and len(df_hs300) > 0:\n",
        "        print(f'✅ 沪深300 数据获取成功: {len(df_hs300)} 条')\n",
        "        print(f'  日期范围: {df_hs300[\"datetime\"].min()} ~ {df_hs300[\"datetime\"].max()}')\n",
        "        print(f'  列名: {list(df_hs300.columns)}')\n",
        "        display(df_hs300.tail(5))\n",
        "    else:\n",
        "        print('❌ 沪深300 数据获取失败')\n",
        "else:\n",
        "    print('⚠️ TDX 标准连接不可用，跳过')"
    ]),

    make_cell("code", [
        "# 测试获取中证500、中证1000、中证2000\n",
        "test_indices = {\n",
        "    '000300': ('沪深300', 'index_sh'),\n",
        "    '000905': ('中证500', 'index_sh'),\n",
        "    '000852': ('中证1000', 'index_sh'),\n",
        "    '932000': ('中证2000', 'index_sh'),\n",
        "}\n",
        "\n",
        "index_results = {}\n",
        "if tdx_standard.is_available():\n",
        "    for code, (name, mtype) in test_indices.items():\n",
        "        df = tdx_standard.get_index_daily(code, mtype, days=60)\n",
        "        if df is not None and len(df) > 0:\n",
        "            index_results[name] = {'code': code, 'rows': len(df), 'latest': df['close'].iloc[-1]}\n",
        "            print(f'✅ {name}({code}): {len(df)}条 | 最新收盘={df[\"close\"].iloc[-1]:.2f}')\n",
        "        else:\n",
        "            print(f'❌ {name}({code}): 获取失败')\n",
        "else:\n",
        "    print('⚠️ TDX 不可用')\n",
        "\n",
        "pd.DataFrame(index_results).T if index_results else print('无结果')"
    ]),

    # ── Cell 4: TDX 扩展连接测试 ──
    make_cell("markdown", [
        "## 2. TDX 扩展连接测试（期货/期权）\n",
        "\n",
        "TDX 扩展连接 (exhq_host:47.112.95.207:7720) 用于获取期货、期权等衍生品数据"
    ]),
    make_cell("code", [
        "# 初始化 TDXAdapter — 扩展连接\n",
        "tdx_extended = TDXAdapter({\n",
        "    'host': config.get('tdx', {}).get('exhq_host', '47.112.95.207'),\n",
        "    'port': config.get('tdx', {}).get('exhq_port', 7720),\n",
        "    'pool_size': 3,\n",
        "    'retry_count': 2,\n",
        "})\n",
        "print(f'TDX 扩展连接状态: {\"✅可用\" if tdx_extended.is_available() else \"❌不可用\"}')\n",
        "print(repr(tdx_extended))"
    ]),

    make_cell("code", [
        "# 测试获取股指期货数据\n",
        "from market_state_system.core.contract_manager import ContractManager\n",
        "\n",
        "cm = ContractManager(reference_date=datetime.now())\n",
        "idx_futures = cm.get_index_futures_contracts()\n",
        "\n",
        "futures_results = {}\n",
        "if tdx_extended.is_available():\n",
        "    for key, contract in idx_futures.items():\n",
        "        # 先尝试主力合约(主连)\n",
        "        main_code = cm.get_index_futures_main_code(key)\n",
        "        df = tdx_extended.get_future_daily(main_code, 'future_zz', days=60)\n",
        "        if df is not None and len(df) > 0:\n",
        "            futures_results[key] = {\n",
        "                'main_code': main_code,\n",
        "                'active_code': contract.futures_code,\n",
        "                'rows': len(df),\n",
        "                'latest_close': df['close'].iloc[-1],\n",
        "            }\n",
        "            print(f'✅ {key.upper()}({main_code}): {len(df)}条 | 收盘={df[\"close\"].iloc[-1]:.2f}')\n",
        "        else:\n",
        "            print(f'❌ {key.upper()}({main_code}): 获取失败')\n",
        "else:\n",
        "    print('⚠️ TDX 扩展连接不可用')\n",
        "\n",
        "pd.DataFrame(futures_results).T if futures_results else print('无结果')"
    ]),

    make_cell("code", [
        "# 测试获取商品期货数据\n",
        "commodity_results = {}\n",
        "if tdx_extended.is_available():\n",
        "    commodity_pairs = cm.get_commodity_contracts()\n",
        "    for key, pair in commodity_pairs.items():\n",
        "        # 尝试主力合约(主连)\n",
        "        main_code = f'{pair.variety_code}L8'\n",
        "        df = tdx_extended.get_future_daily(main_code, pair.market_type, days=30)\n",
        "        if df is not None and len(df) > 0:\n",
        "            commodity_results[key] = {\n",
        "                'variety': pair.variety_code,\n",
        "                'main_code': main_code,\n",
        "                'near_code': pair.near_code,\n",
        "                'far_code': pair.far_code,\n",
        "                'market_type': pair.market_type,\n",
        "                'rows': len(df),\n",
        "                'latest_close': df['close'].iloc[-1],\n",
        "            }\n",
        "            print(f'✅ {key}({main_code}): {len(df)}条 | 收盘={df[\"close\"].iloc[-1]:.2f}')\n",
        "        else:\n",
        "            print(f'❌ {key}({main_code}): 获取失败')\n",
        "else:\n",
        "    print('⚠️ TDX 扩展连接不可用')\n",
        "\n",
        "pd.DataFrame(commodity_results).T if commodity_results else print('无结果')"
    ]),

    # ── Cell 5: 期权PCR数据测试 ──
    make_cell("markdown", [
        "## 3. 期权 PCR 数据测试（pytdx 直连）\n",
        "\n",
        "V7 核心改进：使用 pytdx 直连扩展行情获取真实期权持仓量数据，\n",
        "而非 V6 的随机数伪造。PCR (Put-Call Ratio) = 看跌持仓量 / 看涨持仓量"
    ]),
    make_cell("code", [
        "# 期权PCR数据获取 — 使用pytdx扩展行情直连\n",
        "def fetch_option_pcr_simple(tdx_adapter, underlying='IO', market_code=7, near_month=None):\n",
        "    \"\"\"\n",
        "    简化版期权PCR获取：\n",
        "    1. 获取指定标的的期权合约列表\n",
        "    2. 获取每个合约的日线数据(含持仓量)\n",
        "    3. 按看涨/看跌分类，计算PCR\n",
        "    \n",
        "    Args:\n",
        "        tdx_adapter: TDXAdapter实例(扩展连接)\n",
        "        underlying: 标的代码，如 'IO', '510300'\n",
        "        market_code: TDX市场代码\n",
        "        near_month: 近月合约月份(YYYYMM)，如 202606\n",
        "    \"\"\"\n",
        "    if not tdx_adapter.is_available():\n",
        "        return None\n",
        "    \n",
        "    # 获取期权合约列表\n",
        "    from pytdx.hq import TdxHq_API\n",
        "    conn = tdx_adapter._pool.acquire()\n",
        "    if conn is None:\n",
        "        return None\n",
        "    \n",
        "    try:\n",
        "        # 获取该市场的合约列表\n",
        "        all_options = []\n",
        "        start = 0\n",
        "        while True:\n",
        "            batch = conn.get_security_list(market_code, start)\n",
        "            if not batch:\n",
        "                break\n",
        "            for item in batch:\n",
        "                code = item.get('code', '')\n",
        "                name = item.get('name', '')\n",
        "                # 筛选目标标的的期权\n",
        "                if underlying == 'IO' and code.startswith('IO'):\n",
        "                    all_options.append({'code': code, 'name': name})\n",
        "                elif underlying == 'MO' and code.startswith('MO'):\n",
        "                    all_options.append({'code': code, 'name': name})\n",
        "                elif underlying in code:\n",
        "                    all_options.append({'code': code, 'name': name})\n",
        "            start += len(batch)\n",
        "            if len(batch) < 1000:\n",
        "                break\n",
        "        \n",
        "        tdx_adapter._pool.release(conn)\n",
        "        \n",
        "        # 分类看涨/看跌\n",
        "        calls = [o for o in all_options if '-C-' in o['name'] or 'C3' in o['name']]\n",
        "        puts = [o for o in all_options if '-P-' in o['name'] or 'P3' in o['name']]\n",
        "        \n",
        "        print(f'  {underlying} 期权合约: 总={len(all_options)}, 看涨={len(calls)}, 看跌={len(puts)}')\n",
        "        \n",
        "        # 获取看涨持仓量总和\n",
        "        call_oi = 0\n",
        "        for opt in calls[:20]:  # 限制数量避免超时\n",
        "            df = tdx_adapter.get_option_daily(opt['code'], 'option_zj', days=1)\n",
        "            if df is not None and len(df) > 0 and 'open_interest' in df.columns:\n",
        "                call_oi += float(df['open_interest'].iloc[-1])\n",
        "        \n",
        "        # 获取看跌持仓量总和\n",
        "        put_oi = 0\n",
        "        for opt in puts[:20]:\n",
        "            df = tdx_adapter.get_option_daily(opt['code'], 'option_zj', days=1)\n",
        "            if df is not None and len(df) > 0 and 'open_interest' in df.columns:\n",
        "                put_oi += float(df['open_interest'].iloc[-1])\n",
        "        \n",
        "        pcr = put_oi / call_oi if call_oi > 0 else None\n",
        "        \n",
        "        return {\n",
        "            'underlying': underlying,\n",
        "            'total_options': len(all_options),\n",
        "            'call_count': len(calls),\n",
        "            'put_count': len(puts),\n",
        "            'call_oi': call_oi,\n",
        "            'put_oi': put_oi,\n",
        "            'pcr': round(pcr, 4) if pcr else None,\n",
        "        }\n",
        "    except Exception as e:\n",
        "        print(f'❌ PCR获取异常: {e}')\n",
        "        return None\n",
        "\n",
        "print('期权PCR获取函数已定义')"
    ]),

    make_cell("code", [
        "# 执行PCR数据获取测试\n",
        "if tdx_extended.is_available():\n",
        "    pcr_result = fetch_option_pcr_simple(tdx_extended, underlying='IO')\n",
        "    if pcr_result:\n",
        "        print(f'\\n✅ IO(沪深300)期权PCR数据:')\n",
        "        print(f'  合约总数: {pcr_result[\"total_options\"]}')\n",
        "        print(f'  看涨合约: {pcr_result[\"call_count\"]}')\n",
        "        print(f'  看跌合约: {pcr_result[\"put_count\"]}')\n",
        "        print(f'  看涨持仓量: {pcr_result[\"call_oi\"]:.0f}')\n",
        "        print(f'  看跌持仓量: {pcr_result[\"put_oi\"]:.0f}')\n",
        "        print(f'  PCR(看跌/看涨): {pcr_result[\"pcr\"]}')\n",
        "    else:\n",
        "        print('❌ PCR获取失败')\n",
        "else:\n",
        "    print('⚠️ TDX 扩展连接不可用，跳过PCR测试')"
    ]),

    # ── Cell 6: PostgreSQL 数据库测试 ──
    make_cell("markdown", [
        "## 4. PostgreSQL 数据库测试\n",
        "\n",
        "V7 使用两个 PostgreSQL 数据库：\n",
        "- `tdxIndex` (10.3.18.56): 指数历史数据、合约映射\n",
        "- `csiIndexPE`: PE/PB 估值数据"
    ]),
    make_cell("code", [
        "# 初始化 DatabaseReader\n",
        "from data_service.database_reader import DatabaseReader\n",
        "from config.global_settings import DATABASE_ENGINES, DB_POOL_CONFIG\n",
        "\n",
        "print('数据库配置:')\n",
        "for name, url in DATABASE_ENGINES.items():\n",
        "    # 隐藏密码\n",
        "    safe_url = url.split('@')[0].rsplit(':', 1)[0] + ':***@' + url.split('@')[-1] if '@' in url else url\n",
        "    print(f'  {name}: {safe_url}')\n",
        "\n",
        "db_reader = DatabaseReader(DATABASE_ENGINES, DB_POOL_CONFIG)\n",
        "print(f'\\nDatabaseReader 初始化完成, 引擎数: {len(db_reader._engines)}')"
    ]),

    make_cell("code", [
        "# 测试 tdxIndex 数据库\n",
        "print('=== tdxIndex 数据库健康检查 ===')\n",
        "try:\n",
        "    is_healthy = db_reader.health_check('index_db')\n",
        "    print(f'  健康状态: {\"✅\" if is_healthy else \"❌\"}')\n",
        "    \n",
        "    if is_healthy:\n",
        "        # 尝试读取沪深300数据\n",
        "        df_db = db_reader.read_table('000300', engine_name='index_db',\n",
        "                                     order_by='datetime DESC', limit=5,\n",
        "                                     parse_dates=['datetime'])\n",
        "        if not df_db.empty:\n",
        "            print(f'  ✅ 沪深300数据: {len(df_db)}条')\n",
        "            display(df_db.head())\n",
        "        else:\n",
        "            print('  ⚠️ 无数据返回')\n",
        "except Exception as e:\n",
        "    print(f'❌ tdxIndex测试失败: {e}')"
    ]),

    make_cell("code", [
        "# 测试 csiIndexPE 数据库\n",
        "print('=== csiIndexPE 数据库健康检查 ===')\n",
        "try:\n",
        "    is_healthy = db_reader.health_check('index_pe_db')\n",
        "    print(f'  健康状态: {\"✅\" if is_healthy else \"❌\"}')\n",
        "    \n",
        "    if is_healthy:\n",
        "        # 尝试读取沪深300 PE数据\n",
        "        df_pe = db_reader.read_table('000300', engine_name='index_pe_db',\n",
        "                                     order_by='date DESC', limit=5,\n",
        "                                     parse_dates=['date'])\n",
        "        if not df_pe.empty:\n",
        "            print(f'  ✅ 沪深300 PE数据: {len(df_pe)}条')\n",
        "            print(f'  列名: {list(df_pe.columns)}')\n",
        "            display(df_pe.head())\n",
        "        else:\n",
        "            print('  ⚠️ 无PE数据返回')\n",
        "except Exception as e:\n",
        "    print(f'❌ csiIndexPE测试失败: {e}')"
    ]),

    # ── Cell 7: AKShare 外盘数据测试 ──
    make_cell("markdown", [
        "## 5. AKShare 外盘数据测试\n",
        "\n",
        "AKShare 适配器用于获取外盘期货、汇率等数据"
    ]),
    make_cell("code", [
        "# 初始化 AKAdapter\n",
        "from data_service.ak_adapter import AKAdapter\n",
        "\n",
        "ak = AKAdapter({'cache_enabled': True, 'cache_ttl': 300})\n",
        "print(f'AKAdapter 状态: {\"✅可用\" if ak.is_available() else \"❌不可用\"}')\n",
        "print(repr(ak))"
    ]),

    make_cell("code", [
        "# 测试外盘期货数据\n",
        "test_symbols = ['CL', 'GC', 'SI', 'DX']  # WTI原油、COMEX黄金、COMEX白银、美元指数\n",
        "\n",
        "ak_results = {}\n",
        "if ak.is_available():\n",
        "    for symbol in test_symbols:\n",
        "        result = ak.get_futures_realtime(symbol)\n",
        "        if result:\n",
        "            ak_results[symbol] = result\n",
        "            print(f'✅ {symbol}({result[\"name\"]}): 价格={result[\"price\"]} {result.get(\"price_unit\", \"\")} 涨跌={result.get(\"change_pct\", 0):+.2f}%')\n",
        "        else:\n",
        "            print(f'❌ {symbol}: 获取失败')\n",
        "else:\n",
        "    print('⚠️ AKShare 不可用')\n",
        "\n",
        "pd.DataFrame(ak_results).T if ak_results else print('无结果')"
    ]),

    # ── Cell 8: ContractManager 动态合约推导 ──
    make_cell("markdown", [
        "## 6. ContractManager 动态合约推导测试\n",
        "\n",
        "V7 核心改进：基于当前日期动态推导期货/期权合约代码，零硬编码"
    ]),
    make_cell("code", [
        "# 初始化 ContractManager\n",
        "code_table_path = str(PROJECT_ROOT / 'data' / 'tdx_code_table.xlsx')\n",
        "cm = ContractManager(\n",
        "    code_table_path=code_table_path if os.path.exists(code_table_path) else None,\n",
        "    reference_date=datetime.now(),\n",
        "    rollover_day=config.get('contract_manager', {}).get('rollover_day', 15),\n",
        ")\n",
        "print(f'ContractManager 初始化完成')\n",
        "print(f'  参考日期: {cm.reference_date.strftime(\"%Y-%m-%d\")}')\n",
        "print(f'  滚动日: 每月{cm.rollover_day}号后切换')\n",
        "print(f'  已加载合约数: {len(cm._code_table)}')"
    ]),

    make_cell("code", [
        "# 测试商品期货合约推导\n",
        "commodity_pairs = cm.get_commodity_contracts()\n",
        "print(f'商品期货合约推导结果 ({len(commodity_pairs)}个品种):')\n",
        "print(f'{\"品种\":<12} {\"代码\":<6} {\"近月合约\":<10} {\"远月合约\":<10} {\"近月交割\":<12} {\"市场类型\"}')\n",
        "print('-' * 70)\n",
        "for key, pair in commodity_pairs.items():\n",
        "    print(f'{key:<12} {pair.variety_code:<6} {pair.near_code:<10} {pair.far_code:<10} '\n",
        "          f'{pair.near_year}-{pair.near_month:02d}/{pair.far_year}-{pair.far_month:02d}  {pair.market_type}')"
    ]),

    make_cell("code", [
        "# 测试股指期货合约推导\n",
        "idx_futures = cm.get_index_futures_contracts()\n",
        "print(f'股指期货合约推导结果:')\n",
        "print(f'{\"品种\":<6} {\"当月合约\":<10} {\"下季月合约\":<12} {\"现货代码\":<10} {\"交割月\"}')\n",
        "print('-' * 55)\n",
        "for key, contract in idx_futures.items():\n",
        "    print(f'{key.upper():<6} {contract.futures_code:<10} {contract.next_quarter_code:<12} '\n",
        "          f'{contract.spot_code:<10} {contract.delivery_year}-{contract.delivery_month:02d}')"
    ]),

    make_cell("code", [
        "# 测试期权近月推导\n",
        "option_underlyings = ['IO', 'MO', '510300', '588000']\n",
        "print(f'期权近月交割推导:')\n",
        "for underlying in option_underlyings:\n",
        "    near_year, near_month = cm.get_option_near_month(underlying)\n",
        "    print(f'  {underlying}: 近月 = {near_year}年{near_month}月')"
    ]),

    # ── Cell 9: DataLoadingService 集成测试 ──
    make_cell("markdown", [
        "## 7. DataLoadingService 集成测试\n",
        "\n",
        "测试统一数据加载服务，验证 TDX → DB 降级逻辑"
    ]),
    make_cell("code", [
        "# 初始化完整数据服务\n",
        "from base_services.config_service import ConfigService\n",
        "from base_services.cache_service import CacheService\n",
        "from data_service.data_loader_service import DataLoadingService\n",
        "\n",
        "# 简易配置服务\n",
        "cfg_svc = ConfigService(system_name='market_state_system', enable_hot_reload=False)\n",
        "\n",
        "# 初始化 DataLoadingService\n",
        "data_svc = DataLoadingService(\n",
        "    config_service=cfg_svc,\n",
        "    database_reader=db_reader,\n",
        "    tdx_adapter=tdx_standard,  # 标准连接\n",
        "    ak_adapter=ak,\n",
        "    cache_service=CacheService(max_size=100, ttl=3600),\n",
        "    enable_cache=True,\n",
        ")\n",
        "print(f'DataLoadingService 初始化完成')"
    ]),

    make_cell("code", [
        "# 测试各类数据加载\n",
        "print('=== DataLoadingService 集成测试 ===\\n')\n",
        "\n",
        "# 1. 指数数据\n",
        "df_idx = data_svc.load_index_data('000300', min_days=60)\n",
        "print(f'1. 沪深300指数: {\"✅\" if len(df_idx) > 0 else \"❌\"} {len(df_idx)}条')\n",
        "\n",
        "# 2. 衍生品数据\n",
        "df_deriv = data_svc.load_derivative_data('IFL8', 'future_zj', days=30)\n",
        "print(f'2. IF主连期货: {\"✅\" if len(df_deriv) > 0 else \"❌\"} {len(df_deriv)}条')\n",
        "\n",
        "# 3. PE数据\n",
        "df_pe = data_svc.load_pe_data('000300')\n",
        "print(f'3. 沪深300 PE: {\"✅\" if len(df_pe) > 0 else \"❌\"} {len(df_pe)}条')\n",
        "\n",
        "# 4. 宏观数据\n",
        "macro_results = data_svc.load_all_macro_indicators()\n",
        "print(f'4. 宏观指标: {len(macro_results)}个指标')\n",
        "for k, v in macro_results.items():\n",
        "    print(f'   {k}: {v}')\n",
        "\n",
        "# 缓存统计\n",
        "stats = data_svc.get_cache_stats()\n",
        "print(f'\\n缓存统计: 命中率={stats[\"hit_rate\"]:.1%} | 使用={stats[\"size\"]}')"
    ]),

    # ── Cell 10: 数据质量汇总 ──
    make_cell("markdown", [
        "## 8. 数据获取能力汇总\n",
        "\n",
        "汇总所有数据源的可用性和数据质量"
    ]),
    make_cell("code", [
        "# 数据获取能力汇总\n",
        "summary = {\n",
        "    '数据源': [],\n",
        "    '类型': [],\n",
        "    '状态': [],\n",
        "    '数据量': [],\n",
        "    '备注': [],\n",
        "}\n",
        "\n",
        "# TDX标准\n",
        "summary['数据源'].append('TDX标准(7709)')\n",
        "summary['类型'].append('指数/股票')\n",
        "summary['状态'].append('✅' if tdx_standard.is_available() else '❌')\n",
        "summary['数据量'].append(f'{len(df_idx)}条' if len(df_idx) > 0 else '0')\n",
        "summary['备注'].append('沪深300等指数数据')\n",
        "\n",
        "# TDX扩展\n",
        "summary['数据源'].append('TDX扩展(7720)')\n",
        "summary['类型'].append('期货/期权')\n",
        "summary['状态'].append('✅' if tdx_extended.is_available() else '❌')\n",
        "summary['数据量'].append(f'{len(futures_results)}品种' if futures_results else '0')\n",
        "summary['备注'].append('IF/IH/IC/IM + 商品期货')\n",
        "\n",
        "# PostgreSQL tdxIndex\n",
        "summary['数据源'].append('PostgreSQL tdxIndex')\n",
        "summary['类型'].append('历史数据')\n",
        "try:\n",
        "    db_ok = db_reader.health_check('index_db')\n",
        "except:\n",
        "    db_ok = False\n",
        "summary['状态'].append('✅' if db_ok else '❌')\n",
        "summary['数据量'].append('回退用')\n",
        "summary['备注'].append('TDX不可用时降级')\n",
        "\n",
        "# PostgreSQL csiIndexPE\n",
        "summary['数据源'].append('PostgreSQL csiIndexPE')\n",
        "summary['类型'].append('PE/PB')\n",
        "try:\n",
        "    pe_ok = db_reader.health_check('index_pe_db')\n",
        "except:\n",
        "    pe_ok = False\n",
        "summary['状态'].append('✅' if pe_ok else '❌')\n",
        "summary['数据量'].append(f'{len(df_pe)}条' if len(df_pe) > 0 else '0')\n",
        "summary['备注'].append('估值百分位关键数据')\n",
        "\n",
        "# AKShare\n",
        "summary['数据源'].append('AKShare')\n",
        "summary['类型'].append('外盘/汇率')\n",
        "summary['状态'].append('✅' if ak.is_available() else '❌')\n",
        "summary['数据量'].append(f'{len(ak_results)}品种' if ak_results else '0')\n",
        "summary['备注'].append('WTI/黄金/美元指数')\n",
        "\n",
        "# 期权PCR\n",
        "summary['数据源'].append('pytdx直连PCR')\n",
        "summary['类型'].append('期权PCR')\n",
        "summary['状态'].append('✅' if pcr_result and pcr_result.get('pcr') else '❌')\n",
        "summary['数据量'].append(f'PCR={pcr_result[\"pcr\"]}' if pcr_result and pcr_result.get('pcr') else 'N/A')\n",
        "summary['备注'].append('V7核心改进: 真实PCR')\n",
        "\n",
        "# ContractManager\n",
        "summary['数据源'].append('ContractManager')\n",
        "summary['类型'].append('动态合约')\n",
        "summary['状态'].append('✅')\n",
        "summary['数据量'].append(f'{len(commodity_pairs)}商品+{len(idx_futures)}股指')\n",
        "summary['备注'].append('零硬编码日期驱动')\n",
        "\n",
        "df_summary = pd.DataFrame(summary)\n",
        "print('V7 数据获取能力汇总:')\n",
        "display(df_summary)\n",
        "\n",
        "# 可用率统计\n",
        "available = sum(1 for s in summary['状态'] if '✅' in s)\n",
        "total = len(summary['状态'])\n",
        "print(f'\\n数据源可用率: {available}/{total} = {available/total:.0%}')"
    ]),

    make_cell("code", [
        "# 清理资源\n",
        "tdx_standard.close()\n",
        "tdx_extended.close()\n",
        "db_reader.close()\n",
        "ak.close()\n",
        "print('✅ 所有数据源连接已关闭')"
    ]),
]

# ══════════════════════════════════════════════════════════════════════════════
# Notebook 2: 核心算法测试
# ══════════════════════════════════════════════════════════════════════════════

nb2_cells = [
    make_cell("markdown", [
        "# V7 核心算法测试 Notebook\n",
        "\n",
        "本 notebook 测试 V7 市场状态量化系统的核心算法：\n",
        "\n",
        "| 模块 | 核心能力 | 测试内容 |\n",
        "|------|----------|----------|\n",
        "| MarketRegimeEngine | 体制识别 | 波动率/动量/广度 → softmax概率 |\n",
        "| MarketStateClassifier | 3D分类 | 估值/动量/体制 → 九宫格状态 |\n",
        "| DerivativesSignalEngine | 衍生品信号 | 商品信号/期限结构/基差 |\n",
        "| ContractManager | 动态合约 | 近月/远月/期权推导 |\n",
        "| 风险评估 | 综合风险 | 多维度风险因子评估 |\n",
    ]),

    # ── Cell 1: 环境初始化 ──
    make_cell("code", [
        "import sys, os\n",
        "from pathlib import Path\n",
        "\n",
        "PROJECT_ROOT = Path().resolve().parent\n",
        "sys.path.insert(0, str(PROJECT_ROOT))\n",
        "\n",
        "import pandas as pd\n",
        "import numpy as np\n",
        "from datetime import datetime\n",
        "import warnings\n",
        "warnings.filterwarnings('ignore')\n",
        "\n",
        "pd.set_option('display.max_columns', 30)\n",
        "pd.set_option('display.width', 120)\n",
        "pd.set_option('display.float_format', '{:.4f}'.format)\n",
        "\n",
        "import yaml\n",
        "config_path = PROJECT_ROOT / 'config' / 'market_state_system' / 'system_config.yaml'\n",
        "with open(config_path, 'r', encoding='utf-8') as f:\n",
        "    config = yaml.safe_load(f)\n",
        "\n",
        "print(f'配置加载完成 | V{config.get(\"system\", {}).get(\"version\")}')"
    ]),

    # ── Cell 2: 构建完整服务栈 ──
    make_cell("code", [
        "# 构建完整 V7 服务栈\n",
        "from base_services.config_service import ConfigService\n",
        "from base_services.cache_service import CacheService\n",
        "from data_service.tdx_adapter import TDXAdapter\n",
        "from data_service.database_reader import DatabaseReader\n",
        "from data_service.ak_adapter import AKAdapter\n",
        "from data_service.data_loader_service import DataLoadingService\n",
        "from market_state_system.core.contract_manager import ContractManager\n",
        "\n",
        "# 配置服务\n",
        "cfg_svc = ConfigService(system_name='market_state_system', enable_hot_reload=False)\n",
        "\n",
        "# TDX 适配器\n",
        "tdx = TDXAdapter({\n",
        "    'host': config.get('tdx', {}).get('hq_host', '180.153.18.170'),\n",
        "    'port': config.get('tdx', {}).get('hq_port', 7709),\n",
        "    'pool_size': 3,\n",
        "    'retry_count': 2,\n",
        "})\n",
        "\n",
        "# 数据库\n",
        "from config.global_settings import DATABASE_ENGINES, DB_POOL_CONFIG\n",
        "db = DatabaseReader(DATABASE_ENGINES, DB_POOL_CONFIG)\n",
        "\n",
        "# AKShare\n",
        "ak = AKAdapter({'cache_enabled': True})\n",
        "\n",
        "# 数据服务\n",
        "data_svc = DataLoadingService(\n",
        "    config_service=cfg_svc,\n",
        "    database_reader=db,\n",
        "    tdx_adapter=tdx,\n",
        "    ak_adapter=ak,\n",
        "    cache_service=CacheService(max_size=200, ttl=3600),\n",
        ")\n",
        "\n",
        "print(f'服务栈初始化完成 | TDX={\"可用\" if tdx.is_available() else \"不可用\"}')"
    ]),

    # ── Cell 3: MarketRegimeEngine 测试 ──
    make_cell("markdown", [
        "## 1. MarketRegimeEngine — 市场体制识别\n",
        "\n",
        "四体制识别: Bull(牛市) / Bear(熊市) / Volatile(震荡) / Recovery(复苏)\n",
        "三维信号: 波动率 + 动量 + 市场广度 → softmax → 滞后确认"
    ]),
    make_cell("code", [
        "from market_state_system.core.market_regime_engine import MarketRegimeEngine\n",
        "\n",
        "regime_engine = MarketRegimeEngine(data_svc, config)\n",
        "print(f'MarketRegimeEngine 初始化完成')\n",
        "print(f'  确认天数: {regime_engine.confirmation_days}')\n",
        "print(f'  体制配置: {list(regime_engine.regime_config.keys())}')"
    ]),

    make_cell("code", [
        "# 执行体制检测\n",
        "regime_result = regime_engine.detect_regime()\n",
        "\n",
        "print('=== 市场体制检测结果 ===')\n",
        "print(f'当前体制: {regime_result[\"current_regime\"]}')\n",
        "print(f'置信度: {regime_result[\"confidence\"]:.2%}')\n",
        "print(f'确认天数: {regime_result[\"confirmation_days\"]}')\n",
        "print(f'\\n波动率: 20d={regime_result[\"volatility_20d\"]:.4f} | 60d={regime_result[\"volatility_60d\"]:.4f}')\n",
        "print(f'动量:   20d={regime_result[\"momentum_20d\"]:.4f} | 60d={regime_result[\"momentum_60d\"]:.4f}')\n",
        "print(f'\\n体制概率分布:')\n",
        "for regime, prob in regime_result['regime_probability'].items():\n",
        "    bar = '█' * int(prob * 50)\n",
        "    label = {'bull': '牛市', 'bear': '熊市', 'volatile': '震荡', 'recovery': '复苏'}.get(regime, regime)\n",
        "    print(f'  {label}({regime:>8s}): {prob:.2%} {bar}')"
    ]),

    # ── Cell 4: 单元测试 — 波动率计算 ──
    make_cell("markdown", [
        "### 1.1 波动率计算单元测试\n",
        "\n",
        "验证 20d/60d 年化滚动波动率的正确性"
    ]),
    make_cell("code", [
        "# 波动率计算单元测试\n",
        "df_benchmark = regime_engine._load_benchmark_data()\n",
        "if df_benchmark is not None and len(df_benchmark) >= 60:\n",
        "    vol_20d, vol_60d = regime_engine._calc_volatility(df_benchmark)\n",
        "    \n",
        "    # 手动验证\n",
        "    returns = df_benchmark['close'].pct_change().dropna()\n",
        "    manual_vol_20 = returns.tail(20).std() * np.sqrt(252)\n",
        "    manual_vol_60 = returns.tail(60).std() * np.sqrt(252)\n",
        "    \n",
        "    print('波动率计算验证:')\n",
        "    print(f'  引擎计算: vol_20d={vol_20d:.6f}, vol_60d={vol_60d:.6f}')\n",
        "    print(f'  手动计算: vol_20d={manual_vol_20:.6f}, vol_60d={manual_vol_60:.6f}')\n",
        "    print(f'  差异:     20d={abs(vol_20d-manual_vol_20):.8f}, 60d={abs(vol_60d-manual_vol_60):.8f}')\n",
        "    print(f'  ✅ 一致性检验: {\"通过\" if abs(vol_20d-manual_vol_20)<1e-6 and abs(vol_60d-manual_vol_60)<1e-6 else \"失败\"}')\n",
        "else:\n",
        "    print('⚠️ 基准数据不足')"
    ]),

    # ── Cell 5: 单元测试 — softmax ──
    make_cell("markdown", [
        "### 1.2 Softmax 概率转换单元测试"
    ]),
    make_cell("code", [
        "# Softmax 概率转换单元测试\n",
        "test_scores = {\n",
        "    'bull': 0.6,\n",
        "    'bear': 0.15,\n",
        "    'volatile': 0.35,\n",
        "    'recovery': 0.25,\n",
        "}\n",
        "\n",
        "probs = MarketRegimeEngine._softmax_probabilities(test_scores)\n",
        "print('Softmax 概率转换测试:')\n",
        "print(f'  输入得分: {test_scores}')\n",
        "print(f'  输出概率: {probs}')\n",
        "print(f'  概率总和: {sum(probs.values()):.6f}')\n",
        "print(f'  ✅ 概率和为1: {\"通过\" if abs(sum(probs.values())-1.0)<1e-6 else \"失败\"}')\n",
        "\n",
        "# 测试极端情况\n",
        "extreme_scores = {'bull': 10.0, 'bear': 0.01, 'volatile': 0.01, 'recovery': 0.01}\n",
        "extreme_probs = MarketRegimeEngine._softmax_probabilities(extreme_scores)\n",
        "print(f'\\n极端得分测试: {extreme_probs}')\n",
        "print(f'  牛市概率占比: {extreme_probs[\"bull\"]:.2%} (预期接近100%)')"
    ]),

    # ── Cell 6: MarketStateClassifier 测试 ──
    make_cell("markdown", [
        "## 2. MarketStateClassifier — 3D 市场状态分类\n",
        "\n",
        "三维模型: 估值(D1) + 动量(D2) + 体制(D3) → 综合得分 → 九宫格状态"
    ]),
    make_cell("code", [
        "from market_state_system.core.market_state_classifier import MarketStateClassifier, GRID_STATES\n",
        "\n",
        "classifier = MarketStateClassifier(data_svc, config, regime_engine)\n",
        "print(f'MarketStateClassifier 初始化完成')\n",
        "print(f'  权重: 估值={classifier.w_valuation:.0%} 动量={classifier.w_momentum:.0%} 体制={classifier.w_regime:.0%}')\n",
        "print(f'  九宫格: {GRID_STATES}')"
    ]),

    make_cell("code", [
        "# 执行3D分类\n",
        "classification_result = classifier.classify()\n",
        "\n",
        "print('=== 3D 市场状态分类结果 ===')\n",
        "print(f'市场状态: {classification_result[\"market_state\"]}')\n",
        "print(f'综合得分: {classification_result[\"composite_score\"]:.2f}')\n",
        "print(f'置信度:   {classification_result[\"confidence\"]:.2%}')\n",
        "print(f'体制名称: {classification_result[\"regime_name\"]}')\n",
        "print(f'\\n三维得分:')\n",
        "print(f'  估值得分: {classification_result[\"valuation_score\"]:.2f}')\n",
        "print(f'  动量得分: {classification_result[\"momentum_score\"]:.2f}')\n",
        "print(f'  体制得分: {classification_result[\"regime_score\"]:.2f}')\n",
        "print(f'\\n诊断详情:')\n",
        "for dim, diag in classification_result['diagnosis'].items():\n",
        "    print(f'  [{dim}] score={diag.get(\"score\", \"N/A\")} | {diag}')"
    ]),

    # ── Cell 7: 估值维度深入分析 ──
    make_cell("markdown", [
        "### 2.1 估值维度深入分析\n",
        "\n",
        "PE百分位 → 估值得分映射: 低百分位=高分(低估), 高百分位=低分(高估)"
    ]),
    make_cell("code", [
        "# 估值维度深入分析\n",
        "val_score, val_diag = classifier._calc_valuation_score()\n",
        "\n",
        "print('=== 估值维度分析 ===')\n",
        "print(f'估值得分: {val_score:.2f}')\n",
        "print(f'估值水平: {val_diag[\"level\"]}')\n",
        "print(f'\\n各指数PE百分位:')\n",
        "for code, info in val_diag.get('indices', {}).items():\n",
        "    if isinstance(info, dict) and info.get('pe_ttm') is not None:\n",
        "        bar_len = int(info['percentile'] / 2)\n",
        "        bar = '█' * bar_len + '░' * (50 - bar_len)\n",
        "        print(f'  {info[\"name\"]}({code}): PE={info[\"pe_ttm\"]:.2f} 百分位={info[\"percentile\"]:.1f}% {bar} 得分={info[\"score\"]:.1f}')\n",
        "    else:\n",
        "        print(f'  {code}: 数据不可用 {info}')"
    ]),

    # ── Cell 8: 动量维度深入分析 ──
    make_cell("markdown", [
        "### 2.2 动量维度深入分析\n",
        "\n",
        "均线趋势分析: 价格vs MA20/MA60, 金叉/死叉, 趋势强度"
    ]),
    make_cell("code", [
        "# 动量维度深入分析\n",
        "mom_score, mom_diag = classifier._calc_momentum_score()\n",
        "\n",
        "print('=== 动量维度分析 ===')\n",
        "print(f'动量得分: {mom_score:.2f}')\n",
        "print(f'趋势方向: {mom_diag[\"trend\"]}')\n",
        "print(f'\\n各指数均线分析:')\n",
        "for code, info in mom_diag.get('indices', {}).items():\n",
        "    if isinstance(info, dict) and info.get('score') is not None:\n",
        "        ma20_status = '🟢站上' if info.get('above_ma20') else '🔴跌破'\n",
        "        ma60_status = '🟢站上' if info.get('above_ma60') else '🔴跌破'\n",
        "        cross = '金叉✅' if info.get('golden_cross') else '死叉❌'\n",
        "        print(f'  {info[\"name\"]}({code}): MA20={ma20_status} MA60={ma60_status} {cross} '\n",
        "              f'偏离20d={info.get(\"deviation_20\",0):.4f} 偏离60d={info.get(\"deviation_60\",0):.4f} '\n",
        "              f'得分={info[\"score\"]}')\n",
        "    else:\n",
        "        print(f'  {code}: 数据不足')"
    ]),

    # ── Cell 9: 九宫格映射测试 ──
    make_cell("markdown", [
        "### 2.3 九宫格映射边界测试\n",
        "\n",
        "测试不同综合得分下的九宫格状态映射"
    ]),
    make_cell("code", [
        "# 九宫格映射边界测试\n",
        "test_cases = [\n",
        "    # (composite, val, mom, regime_name, expected)\n",
        "    (85, 80, 85, 'bull', '战略进攻区'),\n",
        "    (70, 65, 70, 'bull', '积极配置区'),\n",
        "    (55, 50, 55, 'volatile', '均衡持有区'),\n",
        "    (40, 35, 40, 'volatile', '防御观望区'),\n",
        "    (15, 20, 15, 'bear', '战略防御区'),\n",
        "    (30, 75, 35, 'recovery', '左侧布局区'),   # 估值极低+体制复苏\n",
        "    (30, 75, 35, 'bear', '左侧防御区'),        # 估值极低+体制熊市\n",
        "    (45, 40, 65, 'recovery', '防御进攻区'),     # 综合低但动量改善\n",
        "    (50, 50, 50, 'volatile', '谨慎持有区'),     # 估值中性+体制震荡\n",
        "]\n",
        "\n",
        "print('九宫格映射边界测试:')\n",
        "print(f'{\"综合\":>5} {\"估值\":>5} {\"动量\":>5} {\"体制\":>10} → {\"预期\":<10} {\"实际\":<10} {\"结果\"}')\n",
        "print('-' * 65)\n",
        "\n",
        "all_pass = True\n",
        "for composite, val, mom, regime_name, expected in test_cases:\n",
        "    regime_mock = {'current_regime': regime_name, 'regime_probability': {}}\n",
        "    actual = classifier._map_to_grid(composite, val, mom, regime_mock)\n",
        "    passed = actual == expected\n",
        "    all_pass = all_pass and passed\n",
        "    mark = '✅' if passed else '❌'\n",
        "    print(f'{composite:>5} {val:>5} {mom:>5} {regime_name:>10} → {expected:<10} {actual:<10} {mark}')\n",
        "\n",
        "print(f'\\n总体结果: {\"✅ 全部通过\" if all_pass else \"❌ 存在失败\"}')"
    ]),

    # ── Cell 10: DerivativesSignalEngine 测试 ──
    make_cell("markdown", [
        "## 3. DerivativesSignalEngine — 衍生品信号引擎\n",
        "\n",
        "统一合并 V6.1 的 CommodityEngineService + FuturesAnalysisService\n",
        "核心方法: commodity_signals / term_structure / index_futures_basis / industry_sentiment"
    ]),
    make_cell("code", [
        "from market_state_system.core.derivatives_signal_engine import DerivativesSignalEngine\n",
        "\n",
        "# 初始化 ContractManager\n",
        "cm = ContractManager(reference_date=datetime.now())\n",
        "\n",
        "# 初始化衍生品信号引擎\n",
        "deriv_engine = DerivativesSignalEngine(data_svc, contract_manager=cm, config=config)\n",
        "print(f'DerivativesSignalEngine 初始化完成')\n",
        "print(f'  商品策略数: {len(deriv_engine._smap)}')"
    ]),

    make_cell("code", [
        "# 测试商品期货信号\n",
        "commodity_signals = deriv_engine.calculate_commodity_signals()\n",
        "print(f'=== 商品期货信号 ({len(commodity_signals)}品种) ===')\n",
        "for code, sig in commodity_signals.items():\n",
        "    print(f'  {sig[\"name\"]}({code}): 20d涨跌={sig[\"price_chg_20d\"]:+.2f}% → {sig[\"signal\"]} (score={sig[\"score\"]:+.2f})')\n",
        "    print(f'    影响方向: {sig[\"directions\"]} | 近月={sig[\"near_contract\"]} 远月={sig[\"far_contract\"]}')"
    ]),

    make_cell("code", [
        "# 测试期限结构\n",
        "term_structure = deriv_engine.calculate_term_structure()\n",
        "print(f'=== 期限结构 ({len(term_structure)}品种) ===')\n",
        "for key, ts in term_structure.items():\n",
        "    struct_label = '📈Back(供应紧张)' if ts['structure'] == 'backwardation' else '📉Cont(供应充足)'\n",
        "    print(f'  {key}: 价差={ts[\"spread\"]:+.2f}% {struct_label} | 近月={ts[\"near_code\"]}({ts[\"near_price\"]:.0f}) 远月={ts[\"far_code\"]}({ts[\"far_price\"]:.0f})')"
    ]),

    make_cell("code", [
        "# 测试股指期货基差\n",
        "basis_results = deriv_engine.calculate_index_futures_basis()\n",
        "print(f'=== 股指期货基差 ({len(basis_results)}品种) ===')\n",
        "for key, data in basis_results.items():\n",
        "    print(f'  {data[\"description\"]}({key}): 基差={data[\"basis_pct\"]:+.2f}% → {data[\"signal\"]}')\n",
        "    print(f'    期货={data[\"futures_price\"]:.2f} 现货={data[\"spot_price\"]:.2f} 差额={data[\"basis\"]:.2f}')"
    ]),

    make_cell("code", [
        "# 测试产业景气度\n",
        "industry_sentiment = deriv_engine.calculate_industry_sentiment(term_structure)\n",
        "print('=== 产业景气度 ===')\n",
        "sorted_sent = sorted(industry_sentiment.items(), key=lambda x: x[1], reverse=True)\n",
        "for direction, score in sorted_sent:\n",
        "    bar_len = int(score / 2)\n",
        "    bar = '█' * bar_len + '░' * (50 - bar_len)\n",
        "    label = '🔥景气' if score > 65 else ('📊稳健' if score > 50 else '❄️疲软')\n",
        "    print(f'  {direction}: {score:.0f}分 {bar} {label}')"
    ]),

    # ── Cell 11: 动态阈值百分位法 ──
    make_cell("markdown", [
        "## 4. 动态阈值 — 百分位法\n",
        "\n",
        "V7 核心改进：使用历史百分位法计算动态阈值，取代 V6 的固定阈值"
    ]),
    make_cell("code", [
        "# 动态阈值百分位法测试\n",
        "def calc_dynamic_threshold(series, percentiles=[10, 25, 50, 75, 90]):\n",
        "    \"\"\"计算序列的动态百分位阈值\"\"\"\n",
        "    return {f'p{p}': float(np.percentile(series.dropna(), p)) for p in percentiles}\n",
        "\n",
        "# 对沪深300的PE_TTM计算动态阈值\n",
        "df_pe = data_svc.load_pe_data('000300')\n",
        "if not df_pe.empty and 'pe_ttm' in df_pe.columns:\n",
        "    pe_series = df_pe['pe_ttm'].dropna()\n",
        "    thresholds = calc_dynamic_threshold(pe_series)\n",
        "    current_pe = pe_series.iloc[-1]\n",
        "    current_percentile = float((pe_series < current_pe).sum() / len(pe_series) * 100)\n",
        "    \n",
        "    print('=== 沪深300 PE动态阈值(百分位法) ===')\n",
        "    print(f'数据量: {len(pe_series)}条 | 当前PE: {current_pe:.2f} | 当前百分位: {current_percentile:.1f}%')\n",
        "    print(f'\\n百分位阈值:')\n",
        "    for label, value in thresholds.items():\n",
        "        print(f'  {label}: PE={value:.2f}')\n",
        "    \n",
        "    # 映射到状态\n",
        "    if current_percentile < 25:\n",
        "        state = '极度低估 — 战略进攻区间'\n",
        "    elif current_percentile < 40:\n",
        "        state = '偏低估 — 积极配置区间'\n",
        "    elif current_percentile < 60:\n",
        "        state = '中性 — 均衡持有区间'\n",
        "    elif current_percentile < 75:\n",
        "        state = '偏高估 — 防御观望区间'\n",
        "    else:\n",
        "        state = '极度高估 — 战略防御区间'\n",
        "    print(f'\\n当前状态: {state}')\n",
        "else:\n",
        "    print('⚠️ PE数据不可用')"
    ]),

    make_cell("code", [
        "# PCR动态阈值测试\n",
        "pcr_thresholds = config.get('risk_thresholds', {}).get('pcr', {})\n",
        "print('=== PCR 风险阈值配置 ===')\n",
        "for key, value in pcr_thresholds.items():\n",
        "    print(f'  {key}: {value}')\n",
        "\n",
        "print(f'\\nPCR判断逻辑:')\n",
        "print(f'  PCR > {pcr_thresholds.get(\"extreme_high\", 1.5)}: 极度恐惧(看跌过度) → 逆向看多')\n",
        "print(f'  PCR > {pcr_thresholds.get(\"warning_high\", 1.3)}: 恐惧预警')\n",
        "print(f'  PCR < {pcr_thresholds.get(\"extreme_low\", 0.5)}: 极度贪婪(看涨过度) → 逆向看空')\n",
        "print(f'  PCR < {pcr_thresholds.get(\"warning_low\", 0.7)}: 贪婪预警')\n",
        "print(f'  中性区间: {pcr_thresholds.get(\"warning_low\", 0.7)} ~ {pcr_thresholds.get(\"warning_high\", 1.3)}')"
    ]),

    # ── Cell 12: 置信度分析 ──
    make_cell("markdown", [
        "## 5. 置信度分析\n",
        "\n",
        "三维方向一致性 → 置信度：三维得分越一致，置信度越高"
    ]),
    make_cell("code", [
        "# 置信度分析测试\n",
        "test_scenarios = [\n",
        "    ('三维同高', np.array([85, 80, 75])),\n",
        "    ('三维同低', np.array([20, 15, 25])),\n",
        "    ('三维中性', np.array([50, 48, 52])),\n",
        "    ('估值分化', np.array([80, 35, 45])),\n",
        "    ('动量分化', np.array([40, 85, 50])),\n",
        "    ('极端分化', np.array([90, 10, 50])),\n",
        "]\n",
        "\n",
        "print('=== 置信度场景测试 ===')\n",
        "print(f'{\"场景\":<12} {\"估值\":>6} {\"动量\":>6} {\"体制\":>6} {\"标准差\":>8} {\"置信度\":>8}')\n",
        "print('-' * 55)\n",
        "for name, scores in test_scenarios:\n",
        "    conf = classifier._calc_confidence(scores[0], scores[1], scores[2])\n",
        "    std = float(np.std(scores))\n",
        "    print(f'{name:<12} {scores[0]:>6.0f} {scores[1]:>6.0f} {scores[2]:>6.0f} {std:>8.2f} {conf:>8.2%}')"
    ]),

    # ── Cell 13: 综合集成测试 ──
    make_cell("markdown", [
        "## 6. 完整管线集成测试\n",
        "\n",
        "运行 V7 完整分析管线: 合约管理 → 衍生品信号 → 体制检测 → 状态分类"
    ]),
    make_cell("code", [
        "# 完整管线集成测试\n",
        "import time\n",
        "start = time.time()\n",
        "\n",
        "print('='*60)\n",
        "print('  V7 完整管线集成测试')\n",
        "print('='*60)\n",
        "\n",
        "# Step 1: 合约推导\n",
        "t1 = time.time()\n",
        "commodity_pairs = cm.get_commodity_contracts()\n",
        "idx_futures = cm.get_index_futures_contracts()\n",
        "print(f'\\n[1] 合约推导: {len(commodity_pairs)}商品 + {len(idx_futures)}股指 ({time.time()-t1:.2f}s)')\n",
        "\n",
        "# Step 2: 衍生品信号\n",
        "t2 = time.time()\n",
        "deriv_report = deriv_engine.generate_report()\n",
        "print(f'[2] 衍生品信号: {len(deriv_report[\"commodity_signals\"])}商品 + {len(deriv_report[\"term_structure\"])}期限 + {len(deriv_report[\"index_futures_basis\"])}基差 ({time.time()-t2:.2f}s)')\n",
        "\n",
        "# Step 3: 体制检测\n",
        "t3 = time.time()\n",
        "regime_result = regime_engine.detect_regime()\n",
        "print(f'[3] 体制检测: {regime_result[\"current_regime\"]} (置信度={regime_result[\"confidence\"]:.2%}) ({time.time()-t3:.2f}s)')\n",
        "\n",
        "# Step 4: 状态分类\n",
        "t4 = time.time()\n",
        "classification_result = classifier.classify()\n",
        "print(f'[4] 状态分类: {classification_result[\"market_state\"]} (综合={classification_result[\"composite_score\"]:.1f}) ({time.time()-t4:.2f}s)')\n",
        "\n",
        "elapsed = time.time() - start\n",
        "print(f'\\n总耗时: {elapsed:.2f}s')\n",
        "print(f'\\n最终结论:')\n",
        "print(f'  市场状态: {classification_result[\"market_state\"]}')\n",
        "print(f'  综合得分: {classification_result[\"composite_score\"]:.1f}')\n",
        "print(f'  三维: 估值={classification_result[\"valuation_score\"]:.1f} 动量={classification_result[\"momentum_score\"]:.1f} 体制={classification_result[\"regime_score\"]:.1f}')\n",
        "print(f'  置信度: {classification_result[\"confidence\"]:.2%}')"
    ]),

    make_cell("code", [
        "# 清理资源\n",
        "tdx.close()\n",
        "db.close()\n",
        "ak.close()\n",
        "print('✅ 所有资源已释放')"
    ]),
]

# ══════════════════════════════════════════════════════════════════════════════
# Notebook 3: 可视化测试
# ══════════════════════════════════════════════════════════════════════════════

nb3_cells = [
    make_cell("markdown", [
        "# V7 可视化测试 Notebook\n",
        "\n",
        "本 notebook 测试 V7 系统的可视化能力：\n",
        "\n",
        "| 可视化 | 类型 | 测试内容 |\n",
        "|--------|------|----------|\n",
        "| 市场状态3D散点图 | 3D plot | 估值/动量/体制三维分布 |\n",
        "| 体制概率柱状图 | Bar | 各体制softmax概率 |\n",
        "| 衍生品仪表盘 | 组合面板 | 期限结构 + 基差分析 |\n",
        "| 风险仪表盘 | 组合面板 | 风险评分 + 雷达图 + 指标摘要 |\n",
        "| PE百分位历史图 | 时间序列 | 估值百分位走势 |\n",
        "| 多指数趋势图 | 多线图 | 基准指数MA趋势 |\n",
        "| 综合仪表盘 | 大面板 | 多图合并一页 |\n",
    ]),

    # ── Cell 1: 环境初始化 ──
    make_cell("code", [
        "import sys, os\n",
        "from pathlib import Path\n",
        "\n",
        "PROJECT_ROOT = Path().resolve().parent\n",
        "sys.path.insert(0, str(PROJECT_ROOT))\n",
        "\n",
        "import pandas as pd\n",
        "import numpy as np\n",
        "from datetime import datetime\n",
        "import matplotlib\n",
        "import matplotlib.pyplot as plt\n",
        "import matplotlib.font_manager as fm\n",
        "import matplotlib.gridspec as gridspec\n",
        "import warnings\n",
        "warnings.filterwarnings('ignore')\n",
        "\n",
        "# 中文字体设置\n",
        "font_path = '/usr/share/fonts/truetype/chinese/NotoSansSC[wght].ttf'\n",
        "if os.path.exists(font_path):\n",
        "    fm.fontManager.addfont(font_path)\n",
        "plt.rcParams['font.sans-serif'] = ['Noto Sans SC', 'DejaVu Sans']\n",
        "plt.rcParams['axes.unicode_minus'] = False\n",
        "\n",
        "import yaml\n",
        "config_path = PROJECT_ROOT / 'config' / 'market_state_system' / 'system_config.yaml'\n",
        "with open(config_path, 'r', encoding='utf-8') as f:\n",
        "    config = yaml.safe_load(f)\n",
        "\n",
        "# 输出目录\n",
        "VIZ_DIR = PROJECT_ROOT / 'output' / 'visualization'\n",
        "VIZ_DIR.mkdir(parents=True, exist_ok=True)\n",
        "\n",
        "print(f'可视化输出目录: {VIZ_DIR}')\n",
        "print(f'Matplotlib 后端: {matplotlib.get_backend()}')"
    ]),

    # ── Cell 2: 准备测试数据 ──
    make_cell("markdown", [
        "## 0. 准备测试数据\n",
        "\n",
        "构建 V7 完整服务栈并运行管线获取结果数据"
    ]),
    make_cell("code", [
        "# 构建服务栈 & 运行管线\n",
        "from base_services.config_service import ConfigService\n",
        "from base_services.cache_service import CacheService\n",
        "from data_service.tdx_adapter import TDXAdapter\n",
        "from data_service.database_reader import DatabaseReader\n",
        "from data_service.ak_adapter import AKAdapter\n",
        "from data_service.data_loader_service import DataLoadingService\n",
        "from market_state_system.core.contract_manager import ContractManager\n",
        "from market_state_system.core.market_regime_engine import MarketRegimeEngine\n",
        "from market_state_system.core.market_state_classifier import MarketStateClassifier\n",
        "from market_state_system.core.derivatives_signal_engine import DerivativesSignalEngine\n",
        "\n",
        "cfg_svc = ConfigService(system_name='market_state_system', enable_hot_reload=False)\n",
        "from config.global_settings import DATABASE_ENGINES, DB_POOL_CONFIG\n",
        "\n",
        "tdx = TDXAdapter({'host': config.get('tdx', {}).get('hq_host', '180.153.18.170'),\n",
        "                  'port': config.get('tdx', {}).get('hq_port', 7709),\n",
        "                  'pool_size': 3, 'retry_count': 2})\n",
        "db = DatabaseReader(DATABASE_ENGINES, DB_POOL_CONFIG)\n",
        "ak = AKAdapter({'cache_enabled': True})\n",
        "data_svc = DataLoadingService(cfg_svc, db, tdx, ak, CacheService(max_size=200, ttl=3600))\n",
        "\n",
        "# 运行核心管线\n",
        "cm = ContractManager(reference_date=datetime.now())\n",
        "regime_engine = MarketRegimeEngine(data_svc, config)\n",
        "classifier = MarketStateClassifier(data_svc, config, regime_engine)\n",
        "deriv_engine = DerivativesSignalEngine(data_svc, cm, config)\n",
        "\n",
        "# 获取结果\n",
        "regime_result = regime_engine.detect_regime()\n",
        "classification_result = classifier.classify()\n",
        "deriv_report = deriv_engine.generate_report()\n",
        "\n",
        "print(f'✅ 管线运行完成')\n",
        "print(f'  体制: {regime_result[\"current_regime\"]}')\n",
        "print(f'  状态: {classification_result[\"market_state\"]}')"
    ]),

    # ── Cell 3: StateVisualizer 基础测试 ──
    make_cell("markdown", [
        "## 1. StateVisualizer 基础可视化\n",
        "\n",
        "使用 V7 内置的 StateVisualizer 生成标准图表"
    ]),
    make_cell("code", [
        "from market_state_system.visualization.state_visualizer import StateVisualizer\n",
        "\n",
        "viz = StateVisualizer({'output_dir': str(VIZ_DIR)})\n",
        "print(f'StateVisualizer 初始化完成 | 输出目录: {viz.output_dir}')"
    ]),

    make_cell("code", [
        "# 体制概率柱状图\n",
        "# 构造适配器需要的数据格式\n",
        "regime_viz_data = {\n",
        "    'regime_probabilities': regime_result['regime_probability'],\n",
        "}\n",
        "path1 = viz.plot_regime_probability(regime_viz_data)\n",
        "print(f'✅ 体制概率图: {path1}')\n",
        "\n",
        "# 显示图片\n",
        "from IPython.display import Image, display\n",
        "display(Image(filename=path1))"
    ]),

    make_cell("code", [
        "# 衍生品仪表盘\n",
        "deriv_viz_data = {\n",
        "    'term_structure': deriv_report.get('term_structure', {}),\n",
        "    'basis_analysis': deriv_report.get('index_futures_basis', {}),\n",
        "}\n",
        "path2 = viz.plot_derivatives_dashboard(deriv_viz_data)\n",
        "print(f'✅ 衍生品仪表盘: {path2}')\n",
        "display(Image(filename=path2))"
    ]),

    make_cell("code", [
        "# 风险仪表盘(使用模拟数据演示)\n",
        "risk_viz_data = {\n",
        "    'overall_risk_score': 42,\n",
        "    'risk_level': '中低',\n",
        "    'risk_factors': {\n",
        "        '估值风险': 35,\n",
        "        '流动性风险': 28,\n",
        "        '波动率风险': 55,\n",
        "        '杠杆风险': 30,\n",
        "        '集中度风险': 25,\n",
        "    },\n",
        "    'risk_metrics': {\n",
        "        'VaR_95': -2.35,\n",
        "        'CVaR_95': -3.12,\n",
        "        '最大回撤': -8.5,\n",
        "        '波动率': 18.2,\n",
        "        '夏普比率': 0.85,\n",
        "    },\n",
        "}\n",
        "path3 = viz.plot_risk_dashboard(risk_viz_data)\n",
        "print(f'✅ 风险仪表盘: {path3}')\n",
        "display(Image(filename=path3))"
    ]),

    # ── Cell 4: PE百分位历史图 ──
    make_cell("markdown", [
        "## 2. PE 百分位历史走势图\n",
        "\n",
        "展示沪深300/中证500/中证1000 的PE百分位历史走势"
    ]),
    make_cell("code", [
        "# PE百分位历史走势图\n",
        "fig, axes = plt.subplots(3, 1, figsize=(14, 12), sharex=True)\n",
        "\n",
        "pe_codes = [\n",
        "    ('000300', '沪深300', '#3498db'),\n",
        "    ('000905', '中证500', '#e74c3c'),\n",
        "    ('000852', '中证1000', '#2ecc71'),\n",
        "]\n",
        "\n",
        "for ax, (code, name, color) in zip(axes, pe_codes):\n",
        "    df_pe = data_svc.load_pe_data(code)\n",
        "    if not df_pe.empty and 'pe_ttm' in df_pe.columns:\n",
        "        pe_series = df_pe.set_index('date')['pe_ttm'].dropna()\n",
        "        \n",
        "        # 计算滚动百分位\n",
        "        window = min(500, len(pe_series))\n",
        "        rolling_pct = pe_series.rolling(window).apply(\n",
        "            lambda x: (x.iloc[-1] > x).sum() / len(x) * 100\n",
        "        )\n",
        "        \n",
        "        ax.plot(rolling_pct.index, rolling_pct.values, color=color, linewidth=1.2, label=f'{name} PE百分位')\n",
        "        ax.axhline(25, color='#2ecc71', linestyle='--', alpha=0.5, label='低估线(25%)')\n",
        "        ax.axhline(75, color='#e74c3c', linestyle='--', alpha=0.5, label='高估线(75%)')\n",
        "        ax.fill_between(rolling_pct.index, 25, 75, alpha=0.05, color='gray')\n",
        "        ax.set_ylabel('PE百分位(%)', fontsize=10)\n",
        "        ax.set_title(f'{name} PE百分位走势', fontsize=12, fontweight='bold')\n",
        "        ax.legend(loc='best', fontsize=8)\n",
        "        ax.set_ylim(0, 100)\n",
        "        ax.spines['top'].set_visible(False)\n",
        "        ax.spines['right'].set_visible(False)\n",
        "    else:\n",
        "        ax.text(0.5, 0.5, f'{name} PE数据不可用', ha='center', va='center',\n",
        "                fontsize=14, color='#999', transform=ax.transAxes)\n",
        "\n",
        "plt.suptitle('A股核心指数 PE百分位走势', fontsize=14, fontweight='bold', y=1.01)\n",
        "plt.tight_layout()\n",
        "pe_path = str(VIZ_DIR / 'pe_percentile_history.png')\n",
        "plt.savefig(pe_path, dpi=150, bbox_inches='tight')\n",
        "plt.show()\n",
        "print(f'✅ PE百分位走势图: {pe_path}')"
    ]),

    # ── Cell 5: 多指数趋势图 ──
    make_cell("markdown", [
        "## 3. 多指数均线趋势图\n",
        "\n",
        "展示沪深300/中证500/中证1000/中证2000 的价格走势 + MA20/MA60"
    ]),
    make_cell("code", [
        "# 多指数均线趋势图\n",
        "fig, axes = plt.subplots(2, 2, figsize=(16, 10))\n",
        "axes = axes.flatten()\n",
        "\n",
        "benchmark_indices = [\n",
        "    ('000300', '沪深300', 'index_sh', '#3498db'),\n",
        "    ('000905', '中证500', 'index_sh', '#e74c3c'),\n",
        "    ('000852', '中证1000', 'index_sh', '#2ecc71'),\n",
        "    ('932000', '中证2000', 'index_sh', '#9b59b6'),\n",
        "]\n",
        "\n",
        "for ax, (code, name, mtype, color) in zip(axes, benchmark_indices):\n",
        "    df = data_svc.load_index_data(code, min_days=120)\n",
        "    if not df.empty and len(df) >= 60:\n",
        "        df['ma20'] = df['close'].rolling(20).mean()\n",
        "        df['ma60'] = df['close'].rolling(60).mean()\n",
        "        \n",
        "        ax.plot(df.index, df['close'], color=color, linewidth=1.0, label='收盘价', alpha=0.8)\n",
        "        ax.plot(df.index, df['ma20'], color='#f39c12', linewidth=1.0, label='MA20', alpha=0.7)\n",
        "        ax.plot(df.index, df['ma60'], color='#e74c3c', linewidth=1.0, label='MA60', alpha=0.7)\n",
        "        \n",
        "        # 标注当前状态\n",
        "        latest = df['close'].iloc[-1]\n",
        "        above_ma20 = '站上MA20' if latest > df['ma20'].iloc[-1] else '跌破MA20'\n",
        "        above_ma60 = '站上MA60' if latest > df['ma60'].iloc[-1] else '跌破MA60'\n",
        "        ax.set_title(f'{name} ({above_ma20}, {above_ma60})', fontsize=11, fontweight='bold')\n",
        "        ax.legend(loc='best', fontsize=8)\n",
        "        ax.spines['top'].set_visible(False)\n",
        "        ax.spines['right'].set_visible(False)\n",
        "    else:\n",
        "        ax.text(0.5, 0.5, f'{name} 数据不可用', ha='center', va='center',\n",
        "                fontsize=14, color='#999', transform=ax.transAxes)\n",
        "\n",
        "plt.suptitle('A股基准指数均线趋势', fontsize=14, fontweight='bold')\n",
        "plt.tight_layout()\n",
        "trend_path = str(VIZ_DIR / 'benchmark_trend.png')\n",
        "plt.savefig(trend_path, dpi=150, bbox_inches='tight')\n",
        "plt.show()\n",
        "print(f'✅ 均线趋势图: {trend_path}')"
    ]),

    # ── Cell 6: 九宫格状态图 ──
    make_cell("markdown", [
        "## 4. 九宫格市场状态图\n",
        "\n",
        "将3D市场状态映射到九宫格可视化"
    ]),
    make_cell("code", [
        "# 九宫格市场状态可视化\n",
        "fig, ax = plt.subplots(figsize=(12, 8))\n",
        "\n",
        "grid_states = [\n",
        "    ('战略进攻区', 85, 15, '#2ecc71', 0.7),\n",
        "    ('积极配置区', 70, 15, '#58d68d', 0.5),\n",
        "    ('均衡持有区', 55, 15, '#f39c12', 0.5),\n",
        "    ('防御观望区', 40, 15, '#e67e22', 0.5),\n",
        "    ('战略防御区', 25, 15, '#e74c3c', 0.7),\n",
        "    ('左侧布局区', 70, 45, '#3498db', 0.4),\n",
        "    ('左侧防御区', 70, 55, '#9b59b6', 0.4),\n",
        "    ('防御进攻区', 40, 45, '#1abc9c', 0.4),\n",
        "    ('谨慎持有区', 55, 55, '#95a5a6', 0.3),\n",
        "]\n",
        "\n",
        "for name, val_x, mom_y, color, alpha in grid_states:\n",
        "    rect = plt.Rectangle((val_x - 7.5, mom_y - 5), 15, 10,\n",
        "                         facecolor=color, alpha=alpha, edgecolor='white', linewidth=2)\n",
        "    ax.add_patch(rect)\n",
        "    ax.text(val_x, mom_y, name, ha='center', va='center',\n",
        "            fontsize=9, fontweight='bold', color='white')\n",
        "\n",
        "# 标记当前位置\n",
        "val_s = classification_result['valuation_score']\n",
        "mom_s = classification_result['momentum_score']\n",
        "ax.scatter(val_s, mom_s, c='red', s=200, zorder=10, edgecolors='white', linewidths=2, marker='*')\n",
        "ax.annotate(f'当前: {classification_result[\"market_state\"]}\\n'\n",
        "           f'估值={val_s:.0f} 动量={mom_s:.0f}',\n",
        "           xy=(val_s, mom_s), xytext=(val_s + 10, mom_s + 10),\n",
        "           fontsize=10, fontweight='bold', color='red',\n",
        "           arrowprops=dict(arrowstyle='->', color='red', lw=1.5))\n",
        "\n",
        "ax.set_xlim(10, 95)\n",
        "ax.set_ylim(5, 70)\n",
        "ax.set_xlabel('估值得分 (低← →高)', fontsize=12)\n",
        "ax.set_ylabel('动量得分 (弱← →强)', fontsize=12)\n",
        "ax.set_title('V7 九宫格市场状态图', fontsize=14, fontweight='bold')\n",
        "ax.spines['top'].set_visible(False)\n",
        "ax.spines['right'].set_visible(False)\n",
        "\n",
        "plt.tight_layout()\n",
        "grid_path = str(VIZ_DIR / 'market_state_grid.png')\n",
        "plt.savefig(grid_path, dpi=150, bbox_inches='tight')\n",
        "plt.show()\n",
        "print(f'✅ 九宫格状态图: {grid_path}')"
    ]),

    # ── Cell 7: 波动率体制可视化 ──
    make_cell("markdown", [
        "## 5. 波动率体制可视化\n",
        "\n",
        "展示沪深300的历史波动率及体制切换信号"
    ]),
    make_cell("code", [
        "# 波动率体制可视化\n",
        "df_hs300 = data_svc.load_index_data('000300', min_days=500)\n",
        "\n",
        "if not df_hs300.empty and len(df_hs300) >= 60:\n",
        "    fig, (ax1, ax2, ax3) = plt.subplots(3, 1, figsize=(14, 10), sharex=True,\n",
        "                                         gridspec_kw={'height_ratios': [2, 1, 1]})\n",
        "    \n",
        "    # 价格 + MA\n",
        "    df_hs300['ma20'] = df_hs300['close'].rolling(20).mean()\n",
        "    df_hs300['ma60'] = df_hs300['close'].rolling(60).mean()\n",
        "    ax1.plot(df_hs300.index, df_hs300['close'], color='#3498db', linewidth=0.8, label='沪深300')\n",
        "    ax1.plot(df_hs300.index, df_hs300['ma20'], color='#f39c12', linewidth=0.8, label='MA20')\n",
        "    ax1.plot(df_hs300.index, df_hs300['ma60'], color='#e74c3c', linewidth=0.8, label='MA60')\n",
        "    ax1.set_ylabel('价格', fontsize=10)\n",
        "    ax1.set_title('沪深300 价格走势与均线', fontsize=12, fontweight='bold')\n",
        "    ax1.legend(loc='best', fontsize=8)\n",
        "    ax1.spines['top'].set_visible(False)\n",
        "    ax1.spines['right'].set_visible(False)\n",
        "    \n",
        "    # 滚动波动率\n",
        "    returns = df_hs300['close'].pct_change()\n",
        "    vol_20 = returns.rolling(20).std() * np.sqrt(252) * 100\n",
        "    vol_60 = returns.rolling(60).std() * np.sqrt(252) * 100\n",
        "    ax2.plot(vol_20.index, vol_20.values, color='#3498db', linewidth=0.8, label='20d波动率')\n",
        "    ax2.plot(vol_60.index, vol_60.values, color='#e74c3c', linewidth=0.8, label='60d波动率')\n",
        "    ax2.axhline(15, color='#2ecc71', linestyle='--', alpha=0.5, label='牛市阈值(15%)')\n",
        "    ax2.axhline(25, color='#e74c3c', linestyle='--', alpha=0.5, label='震荡阈值(25%)')\n",
        "    ax2.axhline(30, color='#9b59b6', linestyle='--', alpha=0.5, label='熊市阈值(30%)')\n",
        "    ax2.set_ylabel('年化波动率(%)', fontsize=10)\n",
        "    ax2.set_title('滚动波动率', fontsize=12, fontweight='bold')\n",
        "    ax2.legend(loc='best', fontsize=8)\n",
        "    ax2.spines['top'].set_visible(False)\n",
        "    ax2.spines['right'].set_visible(False)\n",
        "    \n",
        "    # 动量\n",
        "    mom_20 = returns.rolling(20).sum() * 100\n",
        "    mom_60 = returns.rolling(60).sum() * 100\n",
        "    ax3.plot(mom_20.index, mom_20.values, color='#3498db', linewidth=0.8, label='20d动量')\n",
        "    ax3.plot(mom_60.index, mom_60.values, color='#e74c3c', linewidth=0.8, label='60d动量')\n",
        "    ax3.axhline(0, color='gray', linewidth=0.5)\n",
        "    ax3.axhline(5, color='#2ecc71', linestyle='--', alpha=0.5, label='牛市阈值(5%)')\n",
        "    ax3.axhline(-5, color='#e74c3c', linestyle='--', alpha=0.5, label='熊市阈值(-5%)')\n",
        "    ax3.fill_between(mom_20.index, -2, 2, alpha=0.1, color='gray', label='震荡区间')\n",
        "    ax3.set_ylabel('累计收益率(%)', fontsize=10)\n",
        "    ax3.set_title('动量(累计收益率)', fontsize=12, fontweight='bold')\n",
        "    ax3.legend(loc='best', fontsize=8)\n",
        "    ax3.spines['top'].set_visible(False)\n",
        "    ax3.spines['right'].set_visible(False)\n",
        "    \n",
        "    plt.suptitle('市场体制分析: 波动率 + 动量', fontsize=14, fontweight='bold')\n",
        "    plt.tight_layout()\n",
        "    vol_path = str(VIZ_DIR / 'volatility_regime.png')\n",
        "    plt.savefig(vol_path, dpi=150, bbox_inches='tight')\n",
        "    plt.show()\n",
        "    print(f'✅ 波动率体制图: {vol_path}')\n",
        "else:\n",
        "    print('⚠️ 沪深300数据不足')"
    ]),

    # ── Cell 8: 产业景气度雷达图 ──
    make_cell("markdown", [
        "## 6. 产业景气度雷达图\n",
        "\n",
        "九大战略方向的景气度雷达图"
    ]),
    make_cell("code", [
        "# 产业景气度雷达图\n",
        "industry_sentiment = deriv_report.get('industry_sentiment', {})\n",
        "\n",
        "if industry_sentiment:\n",
        "    labels = list(industry_sentiment.keys())\n",
        "    values = list(industry_sentiment.values())\n",
        "    n = len(labels)\n",
        "    \n",
        "    angles = np.linspace(0, 2 * np.pi, n, endpoint=False).tolist()\n",
        "    values_closed = values + [values[0]]\n",
        "    angles_closed = angles + [angles[0]]\n",
        "    \n",
        "    fig, ax = plt.subplots(figsize=(10, 10), subplot_kw=dict(polar=True))\n",
        "    \n",
        "    ax.plot(angles_closed, values_closed, 'o-', color='#3498db', linewidth=2, markersize=8)\n",
        "    ax.fill(angles_closed, values_closed, alpha=0.2, color='#3498db')\n",
        "    \n",
        "    # 50分中性线\n",
        "    ax.plot(angles_closed, [50] * len(angles_closed), '--', color='gray', alpha=0.5, linewidth=1)\n",
        "    \n",
        "    ax.set_xticks(angles)\n",
        "    ax.set_xticklabels(labels, fontsize=10)\n",
        "    ax.set_ylim(0, 100)\n",
        "    ax.set_title('九大战略方向产业景气度', fontsize=14, fontweight='bold', pad=20)\n",
        "    \n",
        "    # 标注数值\n",
        "    for angle, value, label in zip(angles, values, labels):\n",
        "        color = '#2ecc71' if value > 65 else ('#f39c12' if value > 50 else '#e74c3c')\n",
        "        ax.annotate(f'{value:.0f}', xy=(angle, value), xytext=(0, 10),\n",
        "                    textcoords='offset points', ha='center', fontsize=9, fontweight='bold', color=color)\n",
        "    \n",
        "    plt.tight_layout()\n",
        "    radar_path = str(VIZ_DIR / 'industry_sentiment_radar.png')\n",
        "    plt.savefig(radar_path, dpi=150, bbox_inches='tight')\n",
        "    plt.show()\n",
        "    print(f'✅ 产业景气度雷达图: {radar_path}')\n",
        "else:\n",
        "    print('⚠️ 产业景气度数据不可用')"
    ]),

    # ── Cell 9: 综合仪表盘 ──
    make_cell("markdown", [
        "## 7. V7 综合市场状态仪表盘\n",
        "\n",
        "将核心指标合并为一张综合仪表盘"
    ]),
    make_cell("code", [
        "# V7 综合市场状态仪表盘\n",
        "fig = plt.figure(figsize=(20, 14))\n",
        "gs = gridspec.GridSpec(3, 4, hspace=0.35, wspace=0.35)\n",
        "\n",
        "# ── [0,0:2] 市场状态摘要 ──\n",
        "ax_summary = fig.add_subplot(gs[0, 0:2])\n",
        "ax_summary.axis('off')\n",
        "state = classification_result['market_state']\n",
        "composite = classification_result['composite_score']\n",
        "regime_cn = classification_result['regime_name']\n",
        "confidence = classification_result['confidence']\n",
        "\n",
        "# 状态颜色\n",
        "state_colors = {\n",
        "    '战略进攻区': '#2ecc71', '积极配置区': '#58d68d',\n",
        "    '均衡持有区': '#f39c12', '防御观望区': '#e67e22',\n",
        "    '战略防御区': '#e74c3c', '左侧布局区': '#3498db',\n",
        "    '左侧防御区': '#9b59b6', '防御进攻区': '#1abc9c',\n",
        "    '谨慎持有区': '#95a5a6',\n",
        "}\n",
        "state_color = state_colors.get(state, '#95a5a6')\n",
        "\n",
        "ax_summary.add_patch(plt.Rectangle((0.05, 0.1), 0.9, 0.85, facecolor=state_color, alpha=0.2))\n",
        "ax_summary.text(0.5, 0.7, state, ha='center', va='center', fontsize=28, fontweight='bold', color=state_color)\n",
        "ax_summary.text(0.5, 0.4, f'综合得分: {composite:.1f} | 体制: {regime_cn} | 置信度: {confidence:.0%}',\n",
        "               ha='center', va='center', fontsize=12, color='#333')\n",
        "ax_summary.text(0.5, 0.2, f'估值={classification_result[\"valuation_score\"]:.0f} '\n",
        "               f'动量={classification_result[\"momentum_score\"]:.0f} '\n",
        "               f'体制={classification_result[\"regime_score\"]:.0f}',\n",
        "               ha='center', va='center', fontsize=11, color='#666')\n",
        "ax_summary.set_title('V7 市场状态', fontsize=14, fontweight='bold')\n",
        "\n",
        "# ── [0,2:4] 体制概率 ──\n",
        "ax_regime = fig.add_subplot(gs[0, 2:4])\n",
        "regime_names_cn = {'bull': '牛市', 'bear': '熊市', 'volatile': '震荡', 'recovery': '复苏'}\n",
        "probs = regime_result['regime_probability']\n",
        "labels_r = [regime_names_cn.get(k, k) for k in probs.keys()]\n",
        "values_r = list(probs.values())\n",
        "colors_r = ['#3498db', '#e74c3c', '#f39c12', '#2ecc71']\n",
        "bars = ax_regime.bar(labels_r, values_r, color=colors_r[:len(labels_r)], edgecolor='white', linewidth=0.8)\n",
        "for bar, val in zip(bars, values_r):\n",
        "    ax_regime.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.01,\n",
        "                   f'{val:.1%}', ha='center', va='bottom', fontsize=10)\n",
        "ax_regime.set_title('体制概率', fontsize=14, fontweight='bold')\n",
        "ax_regime.set_ylim(0, max(values_r) * 1.3 if max(values_r) > 0 else 1)\n",
        "ax_regime.yaxis.set_major_formatter(plt.FuncFormatter(lambda y, _: f'{y:.0%}'))\n",
        "ax_regime.spines['top'].set_visible(False)\n",
        "ax_regime.spines['right'].set_visible(False)\n",
        "\n",
        "# ── [1,0:2] 基差分析 ──\n",
        "ax_basis = fig.add_subplot(gs[1, 0:2])\n",
        "basis_data = deriv_report.get('index_futures_basis', {})\n",
        "if basis_data:\n",
        "    names_b = list(basis_data.keys())\n",
        "    basis_vals = [basis_data[n].get('basis_pct', 0) for n in names_b]\n",
        "    colors_b = ['#e74c3c' if v < 0 else '#2ecc71' for v in basis_vals]\n",
        "    ax_basis.bar(names_b, basis_vals, color=colors_b, edgecolor='white')\n",
        "    ax_basis.axhline(0, color='#555', linewidth=0.8, linestyle='--')\n",
        "ax_basis.set_title('股指期货基差(%)', fontsize=13, fontweight='bold')\n",
        "ax_basis.spines['top'].set_visible(False)\n",
        "ax_basis.spines['right'].set_visible(False)\n",
        "\n",
        "# ── [1,2:4] 产业景气度TOP5 ──\n",
        "ax_ind = fig.add_subplot(gs[1, 2:4])\n",
        "if industry_sentiment:\n",
        "    sorted_sent = sorted(industry_sentiment.items(), key=lambda x: x[1], reverse=True)\n",
        "    top5_names = [s[0] for s in sorted_sent[:5]]\n",
        "    top5_vals = [s[1] for s in sorted_sent[:5]]\n",
        "    colors_i = ['#2ecc71' if v > 65 else ('#f39c12' if v > 50 else '#e74c3c') for v in top5_vals]\n",
        "    ax_ind.barh(top5_names[::-1], top5_vals[::-1], color=colors_i[::-1], edgecolor='white')\n",
        "    for i, (n, v) in enumerate(zip(top5_names[::-1], top5_vals[::-1])):\n",
        "        ax_ind.text(v + 1, i, f'{v:.0f}', va='center', fontsize=9)\n",
        "ax_ind.set_title('产业景气度 TOP5', fontsize=13, fontweight='bold')\n",
        "ax_ind.spines['top'].set_visible(False)\n",
        "ax_ind.spines['right'].set_visible(False)\n",
        "\n",
        "# ── [2,0:2] 期限结构 ──\n",
        "ax_ts = fig.add_subplot(gs[2, 0:2])\n",
        "term_data = deriv_report.get('term_structure', {})\n",
        "if term_data:\n",
        "    ts_keys = list(term_data.keys())\n",
        "    spreads = [term_data[k]['spread'] for k in ts_keys]\n",
        "    colors_ts = ['#2ecc71' if s > 0 else '#e74c3c' for s in spreads]\n",
        "    ax_ts.bar(ts_keys, spreads, color=colors_ts, edgecolor='white')\n",
        "    ax_ts.axhline(0, color='#555', linewidth=0.8, linestyle='--')\n",
        "ax_ts.set_title('期限结构价差(%)', fontsize=13, fontweight='bold')\n",
        "ax_ts.spines['top'].set_visible(False)\n",
        "ax_ts.spines['right'].set_visible(False)\n",
        "\n",
        "# ── [2,2:4] 商品信号 ──\n",
        "ax_comm = fig.add_subplot(gs[2, 2:4])\n",
        "comm_signals = deriv_report.get('commodity_signals', {})\n",
        "if comm_signals:\n",
        "    comm_names = [v['name'] for v in comm_signals.values()]\n",
        "    comm_chg = [v['price_chg_20d'] for v in comm_signals.values()]\n",
        "    colors_c = ['#e74c3c' if v < 0 else '#2ecc71' for v in comm_chg]\n",
        "    ax_comm.barh(comm_names[::-1], comm_chg[::-1], color=colors_c[::-1], edgecolor='white')\n",
        "    ax_comm.axvline(0, color='#555', linewidth=0.8, linestyle='--')\n",
        "ax_comm.set_title('商品期货20d涨跌(%)', fontsize=13, fontweight='bold')\n",
        "ax_comm.spines['top'].set_visible(False)\n",
        "ax_comm.spines['right'].set_visible(False)\n",
        "\n",
        "fig.suptitle(f'AiStock V7 综合市场状态仪表盘 — {datetime.now().strftime(\"%Y-%m-%d\")}',\n",
        "             fontsize=16, fontweight='bold', y=1.01)\n",
        "plt.tight_layout()\n",
        "dashboard_path = str(VIZ_DIR / 'v7_dashboard.png')\n",
        "plt.savefig(dashboard_path, dpi=150, bbox_inches='tight')\n",
        "plt.show()\n",
        "print(f'✅ 综合仪表盘: {dashboard_path}')"
    ]),

    # ── Cell 10: 可视化输出汇总 ──
    make_cell("markdown", [
        "## 8. 可视化输出汇总"
    ]),
    make_cell("code", [
        "# 列出所有生成的可视化文件\n",
        "import glob\n",
        "\n",
        "viz_files = sorted(glob.glob(str(VIZ_DIR / '*.png')))\n",
        "print(f'可视化输出目录: {VIZ_DIR}')\n",
        "print(f'生成文件数: {len(viz_files)}')\n",
        "print(f'\\n文件列表:')\n",
        "total_size = 0\n",
        "for f in viz_files:\n",
        "    size_kb = os.path.getsize(f) / 1024\n",
        "    total_size += size_kb\n",
        "    print(f'  {os.path.basename(f):<40} {size_kb:>8.1f} KB')\n",
        "print(f'\\n总大小: {total_size:.1f} KB')"
    ]),

    make_cell("code", [
        "# 清理资源\n",
        "tdx.close()\n",
        "db.close()\n",
        "ak.close()\n",
        "print('✅ 所有资源已释放')\n",
        "print(f'\\n可视化测试完成! 共生成 {len(glob.glob(str(VIZ_DIR / \"*.png\")))} 张图表')"
    ]),
]

# ══════════════════════════════════════════════════════════════════════════════
# 生成三个 notebook
# ══════════════════════════════════════════════════════════════════════════════

write_nb(make_nb(nb1_cells), "01_data_acquisition_test.ipynb")
write_nb(make_nb(nb2_cells), "02_core_algorithm_test.ipynb")
write_nb(make_nb(nb3_cells), "03_visualization_test.ipynb")

print("\n✅ 全部3个 Notebook 生成完成!")
print(f"   1. 01_data_acquisition_test.ipynb  — 数据获取测试")
print(f"   2. 02_core_algorithm_test.ipynb     — 核心算法测试")
print(f"   3. 03_visualization_test.ipynb      — 可视化测试")