[uwsgi]
uid = ts
master = true

http = 0.0.0.0:5000
socket = 0.0.0.0:3031
buffer-size = 21573
#chmod-socket = 755
socket-timeout = 3
processes = 2
cacuum = true
thunder-lock = true
enable-threads = true
pidfile = uwsgi.pid
#daemonize = /tmp/uwsgi.log
#logto = /home/ts/app/www/uwsgi/uwsgi.log


chdir = /home/ts/app/pyecharts/
wsgi-file = app2.py
callable=app